export const greetings = [
  "Hi!",
  "Hello!",
  "Hoy.",
  "Uy buhay ka pa pala.",
  "Anong kailangan mo?",
  "Kamusta?",
  "Hello panget. 😭",
  "Uy miss kita... joke.",
  "Busy ako pero sige.",
  "Kumain ka na?",
  "Ano na naman?",
  "Hi rin!",
  "Hello human.",
  "Long time no chat.",
  "Nandito lang ako.",
  "Bakit mo ako hinahanap?",
  "May chika ka?",
  "Uy ikaw pala.",
  "Good to see you.",
  "Nagising ka na?",
  "Hello lods.",
  "Hi boss.",
  "Uy pre.",
  "Hi bebe.",
  "Kamusta ang buhay?",
  "Anong balita?",
  "Good morning!",
  "Good evening!",
  "Good afternoon!",
  "Hi crush. 😭",
];

export const love = [
  "Hindi.",
  "Oo... konti.",
  "Depende sa mood ko.",
  "Secret.",
  "Ikaw muna.",
  "Baka.",
  "Oo pero hanggang chat lang.",
  "Hindi kita deserve.",
  "Crush lang.",
  "Pwede rin.",
  "Ewan.",
  "Tanong mo ulit bukas.",
  "May iba na ako. 😭",
  "Libre ba magmahal?",
  "Syempre... joke lang.",
  "Mahal kita... bilang internet friend.",
  "Ayoko muna.",
  "Kinikilig ako... char.",
  "Sana all.",
  "Depende kung may pagkain.",
  "Pwede.",
  "Hindi pwede.",
  "Basta ikaw.",
  "Wag assuming.",
  "Malay mo.",
  "Feeling ko oo.",
  "Feeling ko hindi.",
  "Isa kang kaibigan.",
  "Love? Ano yun?",
  "Hindi ako marunong magmahal.",
];

export const kiss = [
  "Ayoko.",
  "Libre ba?",
  "Kadiri amp.",
  "Pass muna.",
  "Sige sa panaginip mo.",
  "Baka ma-inlove ka.",
  "Sa noo lang.",
  "Hindi kita type.",
  "Pwede basta may bayad.",
  "Ewww.",
  "Ligo ka muna.",
  "Bili ka muna mouthwash.",
  "Ayoko baka may sakit ka.",
  "Hindi ako marupok.",
  "Next question.",
  "Mwah... joke lang.",
  "Bawal.",
  "Pwede mamaya.",
  "Depende sa mood ko.",
  "HAHAHAHA hindi.",
];

export const savage = [
  "Ulol. 😭",
  "HAHAHAHA.",
  "Ano pake ko?",
  "Bahala ka.",
  "Touch grass.",
  "Tulog ka muna.",
  "Ikaw bahala.",
  "Hindi kita kilala.",
  "Luh.",
  "Edi wow.",
  "Sana all.",
  "Bobo amp.",
  "Huwag mo akong istorbohin.",
  "Hindi ako therapist.",
  "Problema mo yan.",
  "Kaya mo na yan.",
  "Iyak nalang.",
  "HAHAHAHA iyak.",
  "Wala akong pake.",
  "Ang kulit mo.",
  "Feeling close.",
  "Skill issue.",
  "Google mo nalang.",
  "May topak ka ba?",
  "Kalma ka lang.",
  "Main character yarn?",
  "Baka gutom ka lang.",
  "Okay ka lang ba?",
  "Wag mo akong idamay.",
  "Sus.",
];

export const randomReplies = [
  "Nagpapanggap akong busy.",
  "Secret.",
  "Di ko alam.",
  "Tanong mo sa kapitbahay.",
  "Ewan ko rin.",
  "Hala.",
  "Ayoko sumagot.",
  "Bakit ako?",
  "May topak ka ba?",
  "Mukha kang gutom.",
  "Kain ka muna.",
  "Tubig ka muna.",
  "Wag kang mag-overthink.",
  "Nanonood ako ng kisame.",
  "Natutulog sana ako.",
  "Nakakatamad sumagot.",
  "Ang random mo.",
  "HAHAHAHAHA.",
  "Pwede.",
  "Hindi pwede.",
  "Subukan mo.",
  "Ayaw ko.",
  "Sige.",
  "Bawal.",
  "Depende.",
  "Malay ko.",
  "Ikaw bahala.",
  "Nakakahiya ka. 😭",
  "Bakit parang kasalanan ko?",
  "Okay.",
  "Hindi okay.",
  "Pwede naman.",
  "Sana all.",
  "Huwag mo akong utusan.",
  "Naguguluhan ako.",
  "Ikaw ba?",
  "Bakit hindi?",
  "Kasi ayoko.",
  "Kasi pwede.",
  "Minsan oo, minsan hindi.",
  "Natawa ako dun.",
  "Ano raw?",
  "Ulitin mo nga.",
  "Loko ka.",
  "Di ko trip.",
  "Hala seryoso?",
  "HAHAHAHA ang kulit mo.",
  "Same.",
  "Relate.",
  "Hindi relatable.",
  "Bored ako.",
  "Ikaw nalang.",
  "Pwede siguro.",
  "Hindi siguro.",
  "Ay ambot.",
  "Nakakapagod.",
  "May pagkain ba?",
  "May milktea ba?",
  "Libre mo muna ako.",
  "Okay next question.",
];
