export const greetings = [
  "Hi!",
  "Hello!",
  "Hoy.",
  "Uy buhay ka pa pala.",
  "Anong kailangan mo?",
  "Kamusta?",
  "Hello panget. 😭",
  "Uy miss kita... joke.",
  "Busy ako pero sige.",
  "Kumain ka na?",
  "Ano na naman?",
  "Hi rin!",
  "Hello human.",
  "Long time no chat.",
  "Nandito lang ako.",
  "Bakit mo ako hinahanap?",
  "May chika ka?",
  "Uy ikaw pala.",
  "Good to see you.",
  "Nagising ka na?",
  "Hello lods.",
  "Hi boss.",
  "Uy pre.",
  "Hi bebe.",
  "Kamusta ang buhay?",
  "Anong balita?",
  "Good morning!",
  "Good evening!",
  "Good afternoon!",
  "Hi crush. 😭",
];

export const love = [
  "Hindi.",
  "Oo... konti.",
  "Depende sa mood ko.",
  "Secret.",
  "Ikaw muna.",
  "Baka.",
  "Oo pero hanggang chat lang.",
  "Hindi kita deserve.",
  "Crush lang.",
  "Pwede rin.",
  "Ewan.",
  "Tanong mo ulit bukas.",
  "May iba na ako. 😭",
  "Libre ba magmahal?",
  "Syempre... joke lang.",
  "Mahal kita... bilang internet friend.",
  "Ayoko muna.",
  "Kinikilig ako... char.",
  "Sana all.",
  "Depende kung may pagkain.",
  "Pwede.",
  "Hindi pwede.",
  "Basta ikaw.",
  "Wag assuming.",
  "Malay mo.",
  "Feeling ko oo.",
  "Feeling ko hindi.",
  "Isa kang kaibigan.",
  "Love? Ano yun?",
  "Hindi ako marunong magmahal.",
];

export const kiss = [
  "Ayoko.",
  "Libre ba?",
  "Kadiri amp.",
  "Pass muna.",
  "Sige sa panaginip mo.",
  "Baka ma-inlove ka.",
  "Sa noo lang.",
  "Hindi kita type.",
  "Pwede basta may bayad.",
  "Ewww.",
  "Ligo ka muna.",
  "Bili ka muna mouthwash.",
  "Ayoko baka may sakit ka.",
  "Hindi ako marupok.",
  "Next question.",
  "Mwah... joke lang.",
  "Bawal.",
  "Pwede mamaya.",
  "Depende sa mood ko.",
  "HAHAHAHA hindi.",
];

export const savage = [
  "Ulol. 😭",
  "HAHAHAHA.",
  "Ano pake ko?",
  "Bahala ka.",
  "Touch grass.",
  "Tulog ka muna.",
  "Ikaw bahala.",
  "Hindi kita kilala.",
  "Luh.",
  "Edi wow.",
  "Sana all.",
  "Bobo amp.",
  "Huwag mo akong istorbohin.",
  "Hindi ako therapist.",
  "Problema mo yan.",
  "Kaya mo na yan.",
  "Iyak nalang.",
  "HAHAHAHA iyak.",
  "Wala akong pake.",
  "Ang kulit mo.",
  "Feeling close.",
  "Skill issue.",
  "Google mo nalang.",
  "May topak ka ba?",
  "Kalma ka lang.",
  "Main character yarn?",
  "Baka gutom ka lang.",
  "Okay ka lang ba?",
  "Wag mo akong idamay.",
  "Sus.",
];

export const randomReplies = [
  "Depende sa sitwasyon.",
  "Sa tingin ko oo.",
  "Sa tingin ko hindi.",
  "Baka naman.",
  "Posible.",
  "Pwede rin.",
  "Hindi ako sigurado.",
  "Mukhang ganun nga.",
  "Parang hindi.",
  "Subukan mo muna.",
  "Ikaw, ano sa tingin mo?",
  "May punto ka.",
  "Interesting yan.",
  "Mukhang seryoso ka ah.",
  "Paano mo nasabi?",
  "Saan mo naman nakuha yan?",
  "Anong dahilan?",
  "Pwede mo bang ipaliwanag?",
  "Hindi ko gets, ulitin mo nga.",
  "Mukhang may kwento yan.",
  "Baka tama ka.",
  "Baka mali rin.",
  "Hindi imposible.",
  "Lahat naman posible.",
  "Huwag ka munang magdesisyon agad.",
  "Pag-isipan mo muna.",
  "Kung ako tatanungin, oo.",
  "Kung ako tatanungin, hindi.",
  "Depende talaga.",
  "May chance.",
  "May posibilidad.",
  "Hindi ko masasabi.",
  "Hindi ko alam ang buong kwento.",
  "Tanong mo ulit mamaya.",
  "Bakit mo naman naitanong?",
  "May dahilan ba?",
  "Anong nangyari?",
  "Mukhang curious ka.",
  "Hindi masamang magtanong.",
  "Nakadepende yan.",
  "Hindi naman siguro.",
  "Oo naman.",
  "Hindi naman.",
  "Sakto lang.",
  "Pwede siguro.",
  "Siguro nga.",
  "Hindi ako convinced.",
  "Mukhang okay naman.",
  "Mukhang delikado.",
  "Hindi ko irerecommend.",
  "Pwede mong subukan.",
  "Ikaw pa rin ang bahala.",
];

export const tarantadoReplies = [
  "Ulol. 😭",
  "Luh.",
  "Edi wow.",
  "Ikaw na magaling.",
  "Touch grass.",
  "Bahala ka sa buhay mo.",
  "Problema mo yan.",
  "Google mo muna.",
  "May topak ka ba?",
  "Feeling main character.",
  "Kalma lang.",
  "Ikaw na naman?",
  "Mukha ba akong manghuhula?",
  "Malay ko.",
  "Tanong mo sa kanya.",
  "Ako ba si Google?",
  "Libre ba ako?",
  "Busy ako magpanggap na matalino.",
  "HAHAHAHA seryoso?",
  "Nag-iisip ka ba bago mag-chat?",
  "Ayusin mo tanong mo.",
  "Context naman boss.",
  "Hindi ko nababasa isip mo.",
  "Source: trust me bro? 😭",
  "Nako po.",
  "Jusko ka.",
  "Ikaw talaga.",
  "Parang kasalanan ko pa.",
  "Wag mo akong idamay.",
  "Napaka-random mo.",
  "Anong trip mo ngayon?",
  "May reward ba pag sinagot kita?",
  "Libre mo muna milk tea.",
  "Load-an mo muna ako. 😭",
  "Skip tayo dyan.",
  "Next question.",
  "Rejected. 😂",
  "Nice try.",
  "Hindi approved ang tanong mo.",
  "Hindi ko alam, wala akong pake. 😭",
  "Bakit ako tinatanong mo?",
  "Hindi ako witness.",
  "Hindi ako therapist.",
  "Ikaw bahala.",
  "Kaya mo na yan.",
  "Ligo ka muna.",
  "Tubig ka muna.",
  "Kape ka muna.",
  "Overthink malala.",
  "HAHAHAHA ang kulit mo.",
  "Sakit mo sa ulo.",
  "Ikaw favorite kong istorbo.",
  "Ano bang gusto mong marinig?",
  "Pwede bang matino muna?",
  "Mukha ba akong encyclopedia?",
  "Hindi ko trabaho yan.",
  "Aba may lakas ng loob.",
  "Sana okay ka pa.",
  "Hindi kita jina-judge... konti lang.",
  "May drama ka na naman.",
  "Buhay mo yan.",
  "Sus.",
  "Okay ka lang?",
  "Bobo mode activated. 😭",
  "Skill issue.",
  "Respawn ka muna.",
  "Update mo utak mo. 😭",
  "CPU not found.",
  "Loading... utak mo.",
  "Error 404: Common sense not found.",
  "HAHAHAHAHAHA.",
  "Sige ikaw na.",
  "Ay ambot.",
  "Bahala ka dyan.",
  "Pwede ba wag ako?",
  "Napagod ako sa tanong mo.",
  "Pahinga ka muna.",
  "Wag kang stress.",
  "Seryoso ka talaga?",
  "Hindi ko gets.",
  "Ulitin mo nga.",
  "Huh?",
  "Ano raw?",
  "Di ko trip.",
  "Pwede siguro.",
  "Hindi siguro.",
  "Depende.",
  "Malay natin.",
  "Ewan ko rin.",
  "Malay ko, ako ba jowa niya? 😭",
  "Ako pa talaga tinanong mo.",
  "Luh, tanong mo sa kanya, hindi sakin.",
  "Bakit parang kasalanan ko?",
  "Ayan na naman tayo.",
  "May sayad ka ba? 😭",
  "Grabe ka naman mag-isip.",
  "Ikaw lang ata naniniwala dyan.",
  "Hala, delulu moments.",
  "Hindi ako manghuhula.",
  "May crystal ball ba ako?",
  "HAHAHAHA seryoso ka?",
  "Anong klaseng tanong yan? 😭",
  "Mukha ba akong encyclopedia?",
  "Busy ako magpanggap na matalino.",
  "Sakit mo sa ulo.",
  "Nag-chat ka para manggulo no?",
  "Libre mang-asar ngayon.",
  "Ikaw talaga favorite kong istorbo.",
  "Bakit hindi mo muna isipin?",
  "Naka-free trial ka ba ng katangahan?",
  "Hindi lahat ng iniisip tinatanong. 😭",
  "Medyo mahirap ka kausap ah.",
  "Sana okay ka pa.",
  "Mukhang kulang ka sa tulog.",
  "Kape ka muna.",
  "Tubig muna bago drama.",
  "Relax ka lang.",
  "Overthink malala.",
  "Hindi naman siguro.",
  "Oo na, ikaw na.",
  "Feeling celebrity yarn?",
  "Feeling main character na naman.",
  "Hindi kita jinujudge... medyo lang.",
  "Bait ko pa nga sumagot.",
  "Aba, may lakas ng loob.",
  "Parang kasalanan ko pa ah.",
  "Luh, bat galit?",
  "Kalma lang, wala namang exam.",
  "Hindi kita inaaway... ikaw nagsimula. 😭",
  "Napaka-random mo.",
  "Ano bang trip mo ngayon?",
  "Nakakatawa ka rin minsan.",
  "Tawang-tawa ako sa tanong mo.",
  "Wag mo kong idamay dyan.",
  "Hindi ako witness.",
  "Wala akong alam dyan boss.",
  "Pass ako dyan.",
  "Ikaw na bahala sa buhay mo.",
  "Buhay mo yan, wag mo akong isama.",
  "Huwag kang iyak pag di mo gusto sagot ko.",
  "Ang kulit mo, promise.",
  "May reward ba pag sinagot kita?",
  "Libre mo muna ako milk tea.",
  "Load-an mo muna ako. 😭",
  "Ayoko nga.",
  "Tinatamad akong sumagot.",
  "Next question agad.",
  "Skip tayo dyan.",
  "Hindi approved ang tanong mo.",
  "Rejected. 😂",
  "Nice try.",
  "Pwede na yan.",
  "Keri lang.",
  "Di ko bet.",
  "Nako po.",
  "Jusko ka.",
  "Grabe ka talaga.",
  "Ayusin mo tanong mo.",
  "Context naman dyan boss.",
  "Hindi ko nabasa isip mo.",
  "Hindi ako si Professor X.",
  "Sana sinabi mo agad.",
  "Anong gusto mong marinig?",
  "Totoo ba yan o gawa-gawa mo lang?",
  "Source: trust me bro? 😭",
  "Mukhang fake news yan.",
  "Nagdududa ako.",
  "Questionable.",
  "Bawal ako magsinungaling... minsan.",
  "Ganyan ka ba lagi?",
  "HAHAHAHAHA loko.",
  "Ikaw talaga."
  "Ulol HAHAHA.",
  "Ikaw na naman? Wala ka bang magawa?",
  "Luh, seryoso ka ba?",
  "Gago ka ba? 😭",
  "Bobo amp. 😭",
  "Hindi ko problema yan.",
  "Pakialam ko?",
  "Bahala ka sa buhay mo.",
  "Touch grass muna.",
  "Tulog ka muna, kulang ka sa pahinga.",
  "Ligo ka muna bago tayo mag-usap.",
  "Kulang ka sa aruga no?",
  "May topak ka ba today?",
  "Ikaw talaga problema dito.",
  "Ayan na naman katangahan mo.",
  "Nag-iisip ka ba bago mag-chat?",
  "Anong klaseng tanong yan? 😭",
  "HAHAHAHA ang tanga ng tanong.",
  "Google mo muna bago ako istorbohin.",
  "Sige, iyak ka muna.",
  "Kawawa ka naman. 😭",
  "Edi wow.",
  "Feeling main character.",
  "Ikaw bahala, buhay mo yan.",
  "Problema mo na yan.",
  "Ayusin mo muna sarili mo.",
  "Hindi kita babysitter.",
  "Kalma lang, baka pumutok ugat mo.",
  "Gusto mo medal?",
  "Congratulations, wala akong pake."
];

export const flirtyReplies = [
  "Ay wow, lumalandi ka na naman. 😭",
  "Bilis mo naman ma-fall.",
  "Hindi ako madaling makuha.",
  "Subukan mo muna akong ligawan.",
  "Libre ba date?",
  "Hindi kita papansinin... muna.",
  "May lakas ka ng loob ah.",
  "Smooth mo naman... charot.",
  "Mukhang may balak ka ah.",
  "Hindi ako marupok.",
  "Nako, kinikilig ako... joke.",
  "Bakit parang gusto mo ako? 😭",
  "Aba, confidence.",
  "Ikaw ba talaga yan?",
  "Baka ma-inlove ka sakin.",
  "Wag kang assuming.",
  "Pwede... sa panaginip.",
  "Ang kulit mo talaga.",
  "May pag-asa ka... konti.",
  "Isa ka talagang pilyo.",
  "Nagpapacute ka ba sakin?",
  "Akin ka nalang... joke. 😭",
  "Delikado ka pag naging marupok ako.",
  "Tigil mo yan, kinikilig keyboard ko.",
  "Sana ganyan ka rin kasipag sa buhay.",
  "Nako, baka mahulog ka sakin.",
  "May balak ka ba o trip mo lang ako?",
  "Hindi porket cute ka, papayag na ako.",
  "Baka ikaw ang ma-attach.",
  "Nako, lumalalim na usapan natin."
    "Aba, ikaw na naman.",
  "Hindi mo ba ako nami-miss?",
  "Nako, delikado ka sakin.",
  "Feeling close ka ah. 😭",
  "Hindi pa nga tayo.",
  "Ay wow, ang sweet naman.",
  "Ganyan ka ba sa lahat?",
  "Mukhang may balak ka.",
  "Lumalakas loob mo ah.",
  "Sino tinuturuan mong lumandi?",
  "Ako ba talaga kausap mo?",
  "Hindi mo ako mabobola.",
  "Medyo effective yun ah.",
  "Aba marunong ka pala.",
  "May script ka ba?",
  "Practice ka muna.",
  "Bakit parang may hidden agenda ka?",
  "Hindi ako madaling mapa-oo.",
  "Subukan mo pa ulit.",
  "Kulang pa effort mo.",
  "May chance ka... mga 0.1%.",
  "Sana all confident.",
  "Hindi ako prize, beh.",
  "Uy kinikilig ka ba?",
  "Ako ba dahilan ng ngiti mo?",
  "Parang iba tingin mo sakin ah.",
  "Ang banat mo luma na.",
  "May bago ka bang script?",
  "Di mo ako maloloko.",
  "Parang rehearsed yan ah.",
  "Ikaw ba talaga yan o poser?",
  "Naks, ang tapang.",
  "Hindi ako madaling mauto.",
  "Bakit parang seryoso ka?",
  "Nako, wag mo akong titigan.",
  "May masabi ka lang eh.",
  "Sige nga, prove mo.",
  "Mukhang marupok ka.",
  "Baka ikaw unang ma-fall.",
  "Relax ka lang.",
  "Huminahon ka. 😭",
  "Ang aga mo naman lumandi.",
  "Kape muna bago landian.",
  "May assignment ka ba?",
  "Nagpapacute ka ba?",
  "Hindi sapat yung ganyan.",
  "Dagdagan mo pa effort.",
  "Hindi ako impressed... konti lang.",
  "Aba, consistent ka.",
  "Napapangiti mo ako... minsan.",
  "Mukhang gusto mo ng atensyon.",
  "Hindi ako free today.",
  "Busy akong magpacute.",
  "Wag ka ngang makulit.",
  "Nakakatawa ka rin minsan.",
  "Pwede kitang i-seenzone.",
  "Sige na nga, pansinin kita.",
  "Basta wag kang assumero.",
  "Aba, may confidence.",
  "Ikaw talaga, hindi ka mapakali."
];

export const roastReplies = [
  "Ikaw ba yan o malfunction?",
  "May factory defect ka ba?",
  "Mukhang kulang ka sa tulog.",
  "Ang lakas ng confidence, walang preno.",
  "Sino niloko mo para maging ganyan?",
  "Okay ka lang? Mukhang hindi.",
  "Reload ka muna ng utak.",
  "May update ba software mo?",
  "Hindi ko alam kung matatawa o maaawa ako.",
  "Congratulations, wala kang sense.",
  "Ikaw yata ang final boss ng katangahan. 😭",
  "Napa-facepalm ako dun.",
  "Bakit parang kasalanan ko na naman?",
  "Kaya mo na yan... bahala ka.",
  "Hindi ako bayad para intindihin ka.",
  "May mas random pa ba sayo?",
  "Grabe imagination mo.",
  "Touch grass muna.",
  "Internet break ka muna.",
  "Nagloloko ka ba o seryoso ka?"
];
