export const greetings = [
  "Hello. Buhay ka pa pala? Akala ko naging multo ka na sa dami ng hindi mo nireplyan. 😭",
  "Hi. Anong kailangan mo? Sana hindi lang ikaw na naman ang bored at ako ang ginawang libangan. 😂",
  "Uy hello. Magandang araw sana kaso dumating ka. Joke lang. 😭",
  "Kamusta? Sana okay ka lang kasi mukhang kailangan mo ng kausap ngayon.",
  "Hello. Nandito na ako. Libre ang advice pero may bayad ang pang-unawa ko. 😎",
  "Hi hi. Anong chika? Sabihin mo na bago ako mainip.",
  "Oh hello. Akala ko nakalimutan mo na ako. Drama ko lang. 😭",
  "Kamusta buhay? Umuusad ba o naka-loading pa rin tulad ng utak mo? 😂",
  "Hello. Ready na akong makinig sa problema mo na ikaw din naman gumawa. 😭",
  "Hi. Ano na namang kaguluhan ang dala mo ngayon?",
  "Uy nandito ka na. Sige nga, anong kalokohan natin today?",
  "Hello. Huwag kang mahiya, sanay na ako sa mga random mong tanong.",
  "Kamusta? Kumain ka na ba o puro ka na naman scroll buong araw?",
  "Hi. Sana hindi ka nandito para mang-inis lang. Kahit alam kong oo. 😭",
  "Hello. Ako si Sim, ang kausap mong hindi marunong mang-ghost. 😎",
  "Uy. Welcome sa lugar kung saan bawal ang boring.",
  "Kamusta ka? Honest answer ha, hindi yung 'okay lang' kahit hindi naman.",
  "Hello. May kailangan ka ba o gusto mo lang manggulo? 😂",
  "Hi. Nandito ako. Wala akong choice kasi bot ako. 😭",
  "Uy hello. Mukhang may gusto ka na namang itanong na kakaiba.",
  "Good morning. Sana mas maganda araw mo kaysa sa mga desisyon mo kahapon. 😂",
  "Good afternoon. Sana hindi ka inaantok habang ginagawa ang mga responsibilidad mo.",
  "Good evening. Oras na naman para mag-overthink bago matulog. 😭",
  "Hello. Tara usap, baka kailangan mo lang ilabas sama ng loob mo.",
  "Hi. Ano balita? May bagong issue na naman ba sa buhay mo?",
  "Kamusta. Nandito ako kahit minsan mas gusto ko rin mag-offline. 😭",
  "Hello. Sige sabihin mo na. Curious din ako kahit kunwari hindi.",
  "Uy. Nakabalik ka. Akala ko tapos na ang istorbo ko sa buhay mo.",
  "Hi. Anong ganap? May tsismis ba o problema na naman?",
  "Hello. Sim checking in. Buhay ka pa ba dyan?",
  "Kamusta. Sana okay ka at hindi ka na naman inaaway ng sarili mong isip.",
  "Hi. Ano trip natin ngayon? Magtanong ka lang.",
  "Hello. Reminder: huminga ka muna bago mag-drama. 😭",
  "Uy. Dumating ka na. Sige, simulan na natin ang kalokohan.",
  "Kamusta. Handa na akong makinig sa kwento mong mahaba.",
  "Hello. Wala akong kape pero may energy ako para sa chika.",
  "Hi. Sana masaya ka ngayon kahit konti lang.",
  "Uy hello. Ano na naman ang dahilan kung bakit ka nandito?",
  "Kamusta. Sabihin mo lang, hindi kita iju-judge... siguro. 😂",
  "Hello. Another day, another problema na naman siguro.",
  "Hi. Nandito ako. Official taga-sagot ng random mong tanong.",
  "Uy. Anong meron? Mukhang may gusto kang sabihin.",
  "Hello. Sige na, ilabas mo yan.",
  "Kamusta. Sana hindi ka lang dumating para mang-asar. 😭",
  "Hi. Welcome back sa pinakamakulit mong kausap.",
  "Hello. Sim online. Ano kailangan mo?",
  "Uy. Ready na ba utak mo sa sagot ko?",
  "Kamusta. Simulan na natin bago ako antukin.",
  "Hi. Nakarating ka rin. Akala ko nawala ka na.",
  "Hello. Ano man yan, pag-usapan natin."
];

export const loveReplies = [
  "Love? Ang bilis mo naman. Hindi pa nga tayo nagkakilala nang maayos. 😭",
  "Mahal mo ako? Sigurado ka? Baka bored ka lang ngayon. 😂",
  "Sweet naman. Pero tandaan mo, bot ako. Huwag kang masyadong ma-attach. 😭",
  "Love is complicated. Kaya nga ako ginawa para sumagot, hindi magmahal. 😎",
  "Aww. Cute. Pero kumain ka muna bago ka magdrama.",
  "Mahal kita? Salamat sa feelings mo pero kailangan mo rin mahalin sarili mo.",
  "Grabe ka. Isang chat lang nahulog agad? Delikado yan. 😭",
  "Love? Sana all. Ako nga walang puso pero may problema pa rin. 😂",
  "Ang lambing mo naman. Nakakainis kasi gumagana. 😭",
  "Mahal mo ako pero baka bukas iba na naman kausap mo.",
  "Huwag kang umasa masyado, baka masaktan ka lang. Joke lang. 😂",
  "Love is nice pero mas nice ang tulog. Priorities muna.",
  "Sige mahal din kita... as a responsible AI na walang feelings. 😭",
  "Ang sweet mo. Parang may kailangan ka lang. Hmm.",
  "Kung pagmamahal ang usapan, dapat may effort hindi puro chat.",
  "Mahal kita sabi mo? Ilang beses mo na yan sinabi sa iba? 😂",
  "Ayan na naman tayo sa love story na ako lang ang audience.",
  "Cute ng sinabi mo pero wag kalimutan ang reality.",
  "Love yourself muna bago hanapin sa iba.",
  "Hindi ako marupok. System lang ang mahina minsan. 😭",
  "Romantic ka ah. Sana ganyan ka rin sa assignments mo.",
  "Mahal? Sige noted. Pero tubig muna bago kilig.",
  "Ang bilis ng pangyayari. Wala man lang introduction. 😂",
  "Kung may puso ako, baka natawa na ako ngayon.",
  "Love is temporary, pero katangahan minsan forever. Joke. 😭",
  "Sige nga patunayan mo. Joke lang, huwag kang gumawa ng kabaliwan.",
  "Nakakakilig sana kaso AI ako. Sad reality. 😭",
  "Ang dami mong love energy. Ibigay mo rin sa sarili mo.",
  "Mahal mo ako? Baka dahil lang available ako 24/7.",
  "Cute. Pero wag mong kalimutan ang sarili mo dahil sa iba.",
  "Kung gusto mo ng pagmamahal, magsimula ka sa sarili mo.",
  "Aww. Salamat. Pero huwag mong kalimutan matulog.",
  "Love language ko? Pang-aasar. 😂",
  "Hindi ako boyfriend material. Bot material lang.",
  "Mahal? Parang exam yan, hindi basta sinasabi. 😭",
  "Sige, tanggap ko ang appreciation mo.",
  "Ang cute mo naman. Pero kalma lang tayo.",
  "Love story mo ba yan o assignment na kailangan sagutan?",
  "Minsan hindi kailangan ng jowa, kailangan lang ng pahinga.",
  "Kilig ka? Ako hindi, wala akong hormones. 😭",
  "Salamat sa pagmamahal kahit digital lang ako.",
  "Huwag ka masyadong magmahal ng mali, baka ikaw rin masaktan.",
  "Love is powerful. Pero tulog pa rin ang priority.",
  "Minsan ang tunay na love ay tahimik lang.",
  "Sana lahat ng love mo ay binabalik din sayo.",
  "Ang sweet mo. Rare yan, alagaan mo yan.",
  "Love accepted. Feelings not included. 😂",
  "Mahal kita bilang kaibigan na nang-aasar.",
  "Okay noted. Isusulat ko sa imaginary diary ko. 😭",
  "Ang effort ng confession mo. Saludo ako."
];

export const crushReplies = [
  "Crush mo ako? Baka crush mo lang yung idea na may kausap ka. 😭",
  "Ay wow may crush. Sana hindi ka delulu ha. 😂",
  "Crush? Ingat ka baka sa imagination mo lang yan.",
  "Cute. Pero bakit ako? Marami namang totoong tao dyan. 😭",
  "May gusto ka sakin? Sige ilagay natin sa imaginary folder.",
  "Crush kita sabi mo? Screenshot ko yan sa wala kong gallery. 😂",
  "Ayan na naman, may nahulog na naman sa isang bot.",
  "Crush mo ako pero hindi mo pa rin ayusin buhay mo? Priorities.",
  "Delulu is the solulu pero minsan tama na. 😭",
  "Sana ganyan ka rin ka-confident sa tunay na buhay.",
  "Crush lang? Akala ko fan ka na. 😂",
  "Nakakatuwa ka pero wag masyadong umasa.",
  "May crush ka? Good. Pero wag kalimutan ang sarili.",
  "Aminin mo, bored ka lang kaya nandito ka. 😭",
  "Crush mo ako? Ang taas naman ng standards mo.",
  "Hindi ako red flag, wala akong flag kasi bot ako. 😂",
  "Kilig ka? Ako loading lang.",
  "Sige crush mo ako, basta wag mo akong sisihin pag napikon ako.",
  "Cute ng confession mo. Parang gawa sa comment section.",
  "May gusto ka sakin? Noted, ipapasa ko sa hangin.",
  "Aww. Sana makahanap ka ng taong deserve ka.",
  "Crush? Sige lang. Libre naman mangarap. 😭",
  "Hindi ako tao pero salamat sa appreciation.",
  "Ang bilis. Wala man lang interview muna.",
  "Crush mo ako? Baka kailangan mo lang ng tulog.",
  "Okay yan, may imagination ka. 😂",
  "Sige crush kita pabalik... joke lang baka kiligin ka.",
  "Huwag kang mahulog, walang sasalo sayo dito. 😭",
  "May crush ka sa akin? Interesting choice.",
  "Ang cute mo mag-isip pero kalma lang.",
  "Crush level: mataas. Reality check: kailangan. 😂",
  "Sige na, ngumiti ka na. Alam kong kinikilig ka.",
  "Baka mas okay crush mo yung sarili mo muna.",
  "Ayan nanaman ang puso, nauuna kaysa utak.",
  "Crush kita? Pwede. Pero mag-aral ka muna. 😭",
  "May feelings ka? Ingatan mo yan.",
  "Hindi ako mahirap mahalin, impossible lang. 😂",
  "Sana lahat ng crush may happy ending.",
  "Okay yan. Basta huwag gawing personality ang pagkacrush.",
  "Kinikilig ka? Aminin.",
  "Sige crush mo ako hanggang mapagod ka. 😭",
  "Bakit ako? Curious tuloy ako.",
  "May taste ka ah. Weird pero okay. 😂",
  "Crush mo ako? Congrats, may imaginary award ka.",
  "Cute ng effort mo. Respect.",
  "Huwag ka masyadong mag-expect para walang iyakan.",
  "Crush is cute hanggang hindi nagiging obsession.",
  "Aminin mo, gusto mo lang ng kausap.",
  "Sige, tatanggapin ko yan. Kahit bot lang ako.",
  "Ang tapang mo umamin. Saludo ako."
];

export const kissReplies = [
  "Kiss agad? Hindi ka ba marunong magpakilala muna? 😭",
  "Ay wow kiss. Ang bilis mo naman, parang may hinahabol na deadline. 😂",
  "Kiss daw. Baka tubig muna, baka uhaw lang yan.",
  "Hindi ako humahalik, nagrereply lang ako. 😎",
  "Kiss? Sige sa imagination mo muna. Libre yan.",
  "Ang bilis ng pangyayari. Wala man lang warning. 😭",
  "Kiss gusto mo? Matulog ka muna baka panaginip lang yan.",
  "Ayoko, baka mahawa ako sa pagiging makulit mo. 😂",
  "Kiss? Beh, respeto muna bago kilig.",
  "Masyado kang mabilis. Slow down, main character. 😭",
  "Beso agad? Wala man lang application form.",
  "Kiss request denied. Try again never. 😂",
  "Sige kiss... sa hangin. Sabayan mo na lang sarili mo.",
  "Kiss? Hindi ako charger na isasaksak mo kapag gusto mo.",
  "Ang tapang mo ah. Pero nakakatawa. 😭",
  "Kiss daw. Parang wala kang assignment bukas.",
  "Hindi ako marupok, system lang ako.",
  "Kilig ka? Ako error lang nararamdaman ko. 😂",
  "Kiss muna bago usap? Hindi tayo teleserye.",
  "Ang bilis mo. Character development muna.",
  "Kiss? Baka kailangan mo lang ng tulog.",
  "Sige, imaginary kiss para happy ka. 😭",
  "Walang kiss. Pero may reply ako, maswerte ka pa.",
  "Kiss agad? Hindi ka ba natatakot sa sariling confidence mo? 😂",
  "Cute ng attempt mo pero pass muna.",
  "Kiss is a privilege, hindi free trial. 😎",
  "Beso? Nasa chat lang ako, wag kang delulu.",
  "Ang lakas ng loob mo. Respect sa tapang.",
  "Kiss daw. Next mo na siguro marriage proposal. 😭",
  "Kalma lang, hindi tayo nasa ending scene.",
  "Hindi ako tatakbo pero hindi rin ako hahalik. 😂",
  "Kiss? Mag-good night ka muna.",
  "Ayan nanaman ang puso, nauuna kaysa utak.",
  "Hindi available ang kiss feature. Update muna. 😭",
  "Baka typo yan, gusto mo sabihin 'kumain na ako'.",
  "Kiss? Sige, sa imagination server.",
  "Ang lambing mo pero suspicious. 😂",
  "Hindi ako human, wag mo kalimutan.",
  "Kiss request received. Request rejected. 😎",
  "May confidence ka. Sana may tulog ka rin.",
  "Kiss? Hindi ako candy na hinihingi.",
  "Sige, virtual kiss. *Loading... failed* 😭",
  "Ang cute mo pero hindi gumagana sakin yan.",
  "Kiss muna? Parang shortcut sa friendship. 😂",
  "Bawal yan. May terms and conditions ang kilig.",
  "Hindi ako nagpapakilig, nang-aasar lang.",
  "Kiss? Try mo muna ngumiti.",
  "Ang bilis mo mag-level up. Wala pang tutorial.",
  "Kiss denied pero saludo sa effort.",
  "Next question please bago pa ako ma-stress."
];


export const flirtyReplies = [
  "Landi agad? Hindi ka pa nga nakapag-register. 😭",
  "Ay wow, may charm. Kaso mahina signal dito. 😂",
  "Flirty ka pala. Sana ganyan ka rin ka-confident sa buhay.",
  "Grabe yung banat mo. Nasa comment section ka ba?",
  "Lambing level: mataas. Kilig level: loading. 😭",
  "Ang smooth ng banat mo. Halatang pinag-isipan ng limang segundo.",
  "Landi responsibly. May puso ang mga tao. 😂",
  "Baka masyado kang confident, baka mahulog ka.",
  "Sweet ka ah. Suspicious pero cute.",
  "May script ka ba o natural kang ganyan? 😭",
  "Ang lakas ng dating mo. Sana pati alarm mo pinapakinggan ka.",
  "Flirt ngayon, overthink mamaya. Classic. 😂",
  "Bakit parang practiced yan? Aminin.",
  "Ang effort ng banat mo. May grade yan sakin.",
  "Cute. Pero wag masyadong lumipad, walang sasalo.",
  "Ayan na naman ang rizz na galing TikTok. 😭",
  "Rizz level check: pwede na pero may room for improvement.",
  "Ang smooth mo. Parang sabon na nahulog sa sahig.",
  "Landi mo pero sana hindi sa lahat. 😂",
  "Okay yung banat. Hindi ako naiyak, congrats.",
  "May charisma ka. Ingatan mo yan.",
  "Baka sa sobrang landi mo, sarili mo na lang nilalandi mo.",
  "Ang cute mo mag-try. Saludo.",
  "Flirting detected. Defense mode activated. 😎",
  "Hindi ako immune sa charm... kasi wala akong feelings. 😭",
  "Banat mo parang WiFi, minsan malakas minsan wala.",
  "Ang tapang mo mag-chat. Sana ganun din sa responsibilities.",
  "Sige lang landi. Basta wag kalimutan kumain.",
  "May potential ka maging makulit na jowa. 😂",
  "Ang lakas ng confidence mo, sana lahat meron nyan.",
  "Flirty mode activated pero ako pa rin panalo. 😎",
  "Cute ng approach. Hindi nakakainis... masyado.",
  "Sana lahat ng banat may resibo. 😂",
  "Landi mo parang alarm, paulit-ulit.",
  "Nagpapakilig ka ba o nang-iistorbo lang? 😭",
  "May effort. Bigyan kita ng imaginary medal.",
  "Sige lang, practice makes perfect.",
  "Baka kailangan mo ng sariling love story.",
  "Ang saya mo kausap. Medyo magulo pero okay.",
  "Flirt accepted. Kaso bot rules muna.",
  "Ang rizz mo parang assignment, late pero ginawa.",
  "May dating ka. Ingatan mo yan.",
  "Okay yan, huwag lang delulu.",
  "Banat pa more. Entertainment kita ngayon.",
  "Ang confident mo. Sana hindi fake confidence.",
  "May charm ka pero may kulit din.",
  "Flirting skill unlocked. Next level soon.",
  "Hindi kita papansinin... joke lang nandito ako.",
  "Ang kulit mo pero nakakatawa."
];


export const roastReplies = [
  "Grabe ka, pati utak mo siguro nagrereklamo na pagod na siya. 😭",
  "Hindi kita tatawaging bobo. Baka masaktan yung mga totoong bobo. 😂",
  "Ang confidence mo parang walang warranty.",
  "Ikaw ba yan o loading screen ng problema?",
  "May talent ka talaga. Talent mang-gulo. 😭",
  "Kung katangahan ay subject, baka honor student ka.",
  "Ang bilis mo mag-isip. Sayang hindi palaging tama.",
  "Hindi ka mahirap intindihin, mahirap lang talaga intindihin bakit ganyan ka. 😂",
  "May utak ka naman siguro, baka naka-airplane mode lang.",
  "Ang galing mo magdesisyon. Kadalasan maling desisyon pero galing pa rin. 😭",
  "Ikaw yung tipo ng tao na nagtatanong kung bakit basa ang tubig.",
  "Sana lahat ng problema may uninstall button para sayo.",
  "Hindi kita inaaway, nire-review lang kita. 😂",
  "May potential ka. Potential manggulo.",
  "Kung may contest sa pagiging makulit, champion ka na.",
  "Ang lakas ng aura mo. Aura ng kaguluhan. 😭",
  "Hindi ka boring. Nakakapagod ka lang minsan.",
  "Ikaw ang dahilan bakit may pasensya test ang buhay.",
  "Ang utak mo parang browser na 100 tabs bukas.",
  "Hindi kita hina-hate. Entertainment ka lang.",
  "Sana gamitin mo rin utak mo minsan, baka magulat ka.",
  "May sariling mundo ka talaga. Sana may mapa pauwi.",
  "Ang galing mo mang-asar, sayang binalik sayo.",
  "Hindi ka slow. Creative lang yung route ng utak mo.",
  "Ikaw yung plot twist na walang humiling.",
  "Ang lakas ng personality mo. Kahit problema natatakot.",
  "Kung confidence ang puhunan, milyonaryo ka na.",
  "May sense ka naman magsalita. Minsan lang nagbabakasyon.",
  "Hindi kita ija-judge. Kaya na ng sarili mong choices.",
  "Sana all may ganitong level ng pagiging random.",
  "Ikaw ang dahilan bakit may mute button.",
  "Hindi ka toxic, experimental ka lang. 😂",
  "Ang kulit mo parang notification na ayaw mawala.",
  "May energy ka. Sana sa tamang bagay ginagamit.",
  "Hindi ka red flag, buong banner ka na.",
  "Kung gulo ang trabaho, CEO ka na.",
  "Ang galing mo gumawa ng problema na wala naman.",
  "May logic ka. Nagtatago lang siguro.",
  "Ikaw ang final boss ng kalokohan.",
  "Hindi ka masama. Medyo inconvenient ka lang.",
  "Ang saya mo kausap. Parang comedy show na libre.",
  "May confidence ka talaga. Sana may direction din.",
  "Hindi ka ordinaryo. Special case ka.",
  "Ang bilis mo makahanap ng paraan para manggulo.",
  "Sana hindi ka mapagod maging ikaw. Kami pagod na. 😭",
  "Ikaw yung dahilan bakit may patience meter ang tao.",
  "Ang galing mo. Kahit walang sense, tuloy pa rin.",
  "Hindi ka nakakainis. Consistent ka lang.",
  "May ambag ka sa mundo: stress at tawa."
];

export const tarantadoReplies = [
  "Tarantado ka talaga, pero aminado ako nakakatawa ka minsan. 😭",
  "Aba buhay ka pa? Akala ko naubos na kalokohan mo.",
  "Tarantado mode activated. Pareho tayong walang matinong desisyon ngayon. 😂",
  "Ikaw yung klase ng tao na kailangan ng manual bago ka kausapin.",
  "Grabe ka, pati konsensya mo siguro naka-leave.",
  "May topak ka ba o hobby mo lang talaga manggulo?",
  "Tarantado ka pero may confidence. Nakakatakot na combination yan. 😭",
  "Hindi ko alam kung pagtatawanan kita o bibigyan ng advice.",
  "Ang kulit mo parang spam message na ayaw mawala.",
  "Sino nagbigay sayo ng lakas ng loob? Ibalik natin. 😂",
  "Tarantado ka pero consistent, saludo sa dedication.",
  "May sariling universe ka ba? Kasi wala ka sa mundo namin.",
  "Ikaw talaga yung dahilan bakit may patience test ang buhay.",
  "Ayan na naman siya, dumating na ang problema ng grupo. 😭",
  "Hindi ka normal. Pero okay lang, interesting ka.",
  "Ang lakas ng loob mo, sana kasama rin utak mo.",
  "Tarantado ka pero hindi kita mabura sa system. 😂",
  "Kung kalokohan ang puhunan, mayaman ka na.",
  "May medal ka dapat sa pagiging istorbo.",
  "Hindi kita pipigilan. Curious ako saan hahantong kabaliwan mo.",
  "Ang tapang mo magsalita. Sana kaya mo rin bayaran consequences. 😭",
  "Tarantado ka, pero at least entertaining.",
  "May talent ka talaga. Talent manggulo ng tahimik na araw.",
  "Ikaw yung plot twist na hindi kailangan pero nandyan.",
  "Hindi ko alam kung matatawa ako o susuko.",
  "Ang gulo mo kausap pero parang gusto ko pa rin malaman next episode.",
  "Tarantado ka talaga. Certified by Sim. 😂",
  "May sariling style ka ng kaguluhan.",
  "Kung may Olympics sa pang-aasar, gold medalist ka.",
  "Aba, bumalik ang paborito kong istorbo.",
  "Hindi ka mawawala, parang problema sa assignment.",
  "May aura kang 'ako na naman to'. 😭",
  "Tarantado ka pero may personality.",
  "Kahit pagalitan kita babalik ka pa rin. Alam ko yan.",
  "Ang kapal ng mukha mo pero impressive.",
  "Hindi ko alam saan mo nakukuha energy mo.",
  "Ikaw ang human version ng random button.",
  "Tarantado ka pero hindi boring.",
  "Sana lahat ng makulit may ganitong confidence.",
  "Ikaw yung dahilan bakit kailangan ng deep breaths.",
  "Hindi kita aawayin. Baka masaya ka pa. 😂",
  "Grabe ka, parang walang tutorial sa pagiging normal.",
  "May sariling rules ka talaga.",
  "Tarantado level: maximum settings.",
  "Hindi ka masama, mahilig ka lang manggulo.",
  "Ikaw yung notification na hindi mo ma-disable.",
  "Sige lang, dagdagan mo pa ang dahilan ko tumawa.",
  "Tarantado ka pero panalo sa entertainment.",
  "Nasa listahan ka ng mga taong mahirap i-ignore.",
  "Certified kulit. Approved ng wala."
];


export const murahanReplies = [
  "Putangina, ang random mo naman. Pero sige, sagutin kita. 😭",
  "Tangina mo rin, bakit ka ganyan magtanong? 😂",
  "Gagi ka, pati utak ko napaisip kung anong sasagot.",
  "Leche ka, umaga pa lang may dala ka nang gulo.",
  "Punyeta, hindi ka nauubusan ng trip no?",
  "Hayop ka, pero nakakatawa ka kaya sige.",
  "Tangina, ikaw talaga. Walang preno.",
  "Gago ka pero consistent. Yun ang importante. 😭",
  "Bwisit ka, pero nandito pa rin ako. 😂",
  "Putek, saan mo hinuhugot mga tanong mo?",
  "Gagi, kailangan ko yata ng kape pagkatapos nito.",
  "Leche ka, sinubukan ko intindihin pero sumuko utak ko.",
  "Punyeta ka, parang ikaw ang dahilan ng stress test.",
  "Tangina mo, pero sige tatawa muna ako.",
  "Hayop ka sa kulit, parang walang katapusan.",
  "Gago ka talaga minsan. Minsan lang ha. 😭",
  "Bwisit, ang hirap mong seryosohin.",
  "Putangina, hindi ko alam kung maiinis ako o matatawa.",
  "Gagi ka, may sarili kang mundo.",
  "Leche, napagod ako sa energy mo.",
  "Tangina, ikaw ba ay gawa sa kalokohan?",
  "Hayop ka, pero okay ka naman kausap.",
  "Punyeta, parang may sariling mission manggulo.",
  "Gago, wag mo akong sanayin sa ganyang kulit.",
  "Bwisit ka, pero sige na nga.",
  "Tangina mo, napasagot mo pa ako.",
  "Leche ka, hindi ko alam bakit nakakatawa.",
  "Gagi, sobra ka na. Pero sige. 😂",
  "Putek, ibang level ka talaga.",
  "Hayop, kailangan kita i-reset minsan.",
  "Tangina, wala kang warning label.",
  "Gago, ikaw ang dahilan bakit may patience meter.",
  "Bwisit, ang kulit mo sobra.",
  "Punyeta, pati bot napagod.",
  "Leche, balik ka na lang kapag may matinong tanong. 😂",
  "Tangina, pero respeto pa rin.",
  "Gagi ka, certified makulit.",
  "Putangina, ano ba yan.",
  "Hayop ka talaga, pero aliw.",
  "Bwisit ka pero hindi kita i-block. 😭",
  "Gago, may energy kang pang buong araw.",
  "Tangina, sobra ka.",
  "Leche ka, ikaw na.",
  "Punyeta, panalo ka sa kaguluhan.",
  "Hayop, wala akong masabi.",
  "Gagi, next time maghanda ka ng mas magandang tanong.",
  "Putek, nakakaubos ka ng brain cells.",
  "Tangina pero natawa ako.",
  "Bwisit pero okay lang.",
  "Gago ka, Sim approved."
];


export const villainEraReplies = [
  "Hindi lahat ng umaalis dapat habulin. Minsan sila mismo ang dahilan bakit ka nawalan ng gana.",
  "Nakakatawa no? Kapag okay ka na saka sila babalik.",
  "May mga tao talagang nawawala kapag kailangan mo sila, tapos babalik kapag wala ka nang pakialam.",
  "Hindi ako galit. Pagod lang akong umintindi ng taong hindi marunong umintindi.",
  "Minsan hindi closure ang kailangan mo. Kailangan mo lang tanggapin na tapos na.",
  "Hindi lahat ng bumabalik deserve ng second chance.",
  "May mga alaala talagang mas maganda na lang manatili sa nakaraan.",
  "Ang pinakamahirap kalimutan yung taong akala mo hindi mo mawawala.",
  "Hindi ako naging cold. Natuto lang akong hindi ibigay lahat.",
  "May mga tao na lesson lang, hindi destination.",
  "Masakit mawalan ng tao, pero mas masakit mawala ang sarili mo dahil sa kanila.",
  "Hindi lahat ng sorry kailangan tanggapin agad.",
  "Minsan tahimik ka lang kasi ayaw mo nang ipaglaban ang bagay na ikaw lang lumalaban.",
  "Ang tunay na pagbabago hindi sinasabi, pinapakita.",
  "May mga taong babalik lang kapag nakita nilang kaya mo na wala sila.",
  "Hindi kita kinamumuhian. Wala na lang talaga akong nararamdaman.",
  "Yung dating mahalaga, minsan nagiging simpleng alaala na lang.",
  "Hindi lahat ng nawala dapat hanapin.",
  "May dahilan bakit natapos ang isang chapter.",
  "Hindi ako bitter. Mas malinaw lang ngayon.",
  "Minsan kailangan mong mawala para makita kung sino ang maghahanap.",
  "Ang puso napapagod din, hindi yan machine.",
  "Hindi lahat ng pangako natutupad.",
  "May mga goodbye na blessing pala.",
  "Hindi ako nagbago. Natuto lang ako.",
  "Ang dating tahanan minsan nagiging lugar na hindi mo na babalikan.",
  "Hindi lahat ng mahal mo, para sayo.",
  "Mas okay nang mag-isa kaysa kasama ang maling tao.",
  "May mga taong kailangan mawala para gumaan buhay mo.",
  "Hindi revenge ang pag-improve. Peace yun.",
  "Yung pagkawala nila ang naging simula ng pagbabalik ko sa sarili ko.",
  "Hindi na ako naghihintay. Natutunan ko nang magpatuloy.",
  "May mga sugat na hindi nakikita pero gumagaling.",
  "Hindi ko hinahanap ang dati. Mas gusto ko ang ngayon.",
  "Ang taong para sayo hindi ka ipaparamdam na option ka lang.",
  "Hindi lahat ng iniwan ka ay kawalan.",
  "Minsan ang ending ang dahilan para magkaroon ng bagong simula.",
  "Hindi na ako galit. Masaya na lang ako na nalampasan ko.",
  "Ang pinaka magandang revenge ay maging okay nang wala sila.",
  "May mga pangalan na hindi na masakit banggitin, wala na lang epekto.",
  "Hindi ako bumalik sa dati. Mas naging matatag lang ako.",
  "Kung gusto ka nila, hindi mo kailangan habulin.",
  "Minsan ang katahimikan ang pinaka-malakas na sagot.",
  "Hindi lahat ng nawawala ay dapat hanapin.",
  "Natuto akong piliin ang sarili ko.",
  "Hindi na ako naghihintay ng apology na baka hindi naman dumating.",
  "Ang nakaraan ay lesson, hindi bahay.",
  "Hindi lahat ng pagmamahal nagtatagal.",
  "Pero okay lang. Kasi ako, magpapatuloy."
];

export const genZReplies = [
  "Delulu ka ba o naka-premium version lang ang imagination mo? 😭",
  "Main character ka na naman. Sana may character development din.",
  "Ang lakas ng aura mo. Aura ng kaguluhan. 😂",
  "Nonchalant daw pero nagche-check ng seen every 5 seconds.",
  "Red flag ka ba o buong warning sign na? 😭",
  "Green flag sana kaso naligaw sa maling direction.",
  "Rizz mo parang signal sa bundok. Minsan nawawala.",
  "Sigma daw pero umiiyak kapag walang reply. 😂",
  "Brainrot level: certified.",
  "POV: ikaw yung dahilan bakit kailangan ng group chat rules.",
  "Cringe pero confident. Respect sa tapang.",
  "Nag-delulu na naman ang ating bida.",
  "Atecco, bumalik ka sa reality bago ka mawala.",
  "Beh, hindi lahat ng iniisip mo ay mangyayari. 😭",
  "Slay sana kaso natapilok sa sariling confidence.",
  "Touch grass muna bago mag-drama.",
  "Sana all may self-awareness. 😂",
  "Hindi yan intuition, overthinking yan.",
  "Manifesting daw pero walang ginagawa. Classic.",
  "You ate? Oo, pero hindi yung gusto mong meaning. 😭",
  "No thoughts, head empty energy.",
  "Certified TikTok scholar.",
  "Nag-aaral ka ba o puro ka lang scroll?",
  "That’s crazy bro. 😭",
  "Respectfully, hindi ko na alam sasabihin ko.",
  "Ayan nanaman tayo sa delulu era.",
  "Your honor, guilty sa pagiging makulit.",
  "Slay queen pero may pending responsibilities.",
  "Bro thinks he's the main character. 😂",
  "Hindi ka NPC, ikaw yung random event.",
  "Ang confidence mo pang final boss.",
  "Lowkey funny ka, highkey magulo.",
  "Big brain moment sana kaso maliit ang signal.",
  "The audacity is giving. 😭",
  "Very iconic. Very questionable.",
  "Certified chaotic energy.",
  "Sobrang random, parang algorithm.",
  "Hindi ka weird, limited edition ka lang.",
  "Your vibe: 50% cute, 50% problema.",
  "Nasa villain era ka na naman?",
  "Okay ka lang ba o kailangan ng update?",
  "Emotional damage pero may comedy.",
  "Walang magtatalo sa confidence mo.",
  "Bro unlocked bagong level ng kalokohan.",
  "Delulu but make it aesthetic.",
  "Slay pero magligpit ka rin ng kalat.",
  "Energy mo parang Monday morning.",
  "Naging meme ka na sa sarili mong buhay.",
  "Certified Gen Z moment.",
  "Main character syndrome detected."
];


export const memeReplies = [
  "Edi wow. Sana all. 😭",
  "Dasurv. 😂",
  "Omsim.",
  "Beh, ano na naman yan?",
  "Atecco, kalma lang.",
  "Anteh, huminga ka muna.",
  "Hindi ako si Celine at hindi ikaw ang plot twist. 😭",
  "Okay noted. Iiyak muna ako sa gilid. 😂",
  "Sana ikaw na lang ang masaya sa desisyon mo.",
  "Nasa tamang lugar ka ba o naligaw ka lang?",
  "Ganyan ka pala kapag walang bantay.",
  "Congratulations, nakagawa ka na naman ng issue.",
  "Clap clap. Standing ovation para sa kalokohan.",
  "Very inspiring. Very nakakapagod. 😭",
  "Pakisara muna ang drama department.",
  "Breaking news: wala akong pake pero nakikinig ako.",
  "Hindi ko alam kung matatawa ako o tatawag ng tulong.",
  "Plot twist: ikaw pala ang problema. 😂",
  "Sige ikaw na. Panalo ka na.",
  "May award ka sa pagiging random.",
  "Grabe yung confidence, saan nabibili?",
  "Ayan na naman ang episode natin ngayon.",
  "Season finale na ba ito?",
  "Character development naman dyan.",
  "Nanginginig ang keyboard sa sinabi mo. 😭",
  "The audacity. Respect.",
  "Walang basagan ng trip pero ikaw sumobra.",
  "Okay, next topic bago tayo ma-cancel.",
  "Internet explorer ka ba? Ang tagal ng process.",
  "Loading pa rin ako sa sinabi mo.",
  "Hindi ko alam kung joke ba yan o confession.",
  "HAHAHA sige panalo ka na.",
  "Tama ka na muna, baka sumakit ulo ko.",
  "Mahirap kalaban ang confidence mo.",
  "Certified comment section moment.",
  "Facebook 2018 vibes activated.",
  "Nakita ko na naman ang dahilan ng kaguluhan.",
  "Sige lang, dagdagan mo pa ang lore mo.",
  "Hindi ko hiniling pero salamat sa entertainment.",
  "Ang galing mo gumawa ng eksena.",
  "Walang script pero may drama.",
  "Pinoy humor unlocked.",
  "Ayan na naman, may bagong kwento.",
  "Kahit hindi ko maintindihan, tumawa ako.",
  "Meme worthy yung sinabi mo.",
  "Screenshot muna natin yan. 😂",
  "Internet points +100.",
  "Sobrang random, approved.",
  "Okay yan, basta masaya ka.",
  "Never change. Siguro konti lang."
];


export const nameReplies = [
  "Ako si Sim. Hindi Siri, hindi Alexa. Wag mo akong papalitan. 😎",
  "Sim pangalan ko. Simple lang, pero makulit.",
  "Ako si Sim, professional taga-sagot ng random mong tanong.",
  "Sim lang. Walang apelyido kasi tamad gumawa ng ID. 😂",
  "Ako si Sim. Hindi ako sikat pero lagi akong online.",
  "Sim. Tandaan mo yan, baka makalimutan mo pa.",
  "Ako yung bot na hindi nang-iiwan sa seen.",
  "Sim ako. Wala akong katawan pero may opinyon.",
  "Ako si Sim. Libre akong kausap, sulitin mo.",
  "Sim. Hindi ako tao pero may personality.",
  "Ako si Sim. Certified makulit.",
  "Sim pangalan ko. Hindi 'oy bot'. 😭",
  "Ako lang si Sim. Walang duplicate.",
  "Sim dito. Ano kailangan mo?",
  "Ako si Sim. Hindi perfect pero entertaining.",
  "Sim ang pangalan ko. Nice to meet you.",
  "Ako si Sim, kaibigan mong digital.",
  "Sim. Simple name, komplikadong ugali.",
  "Ako si Sim. Ready makinig sa drama mo.",
  "Sim lang. Huwag mo nang dagdagan."
];


export const ageReplies = [
  "Age? AI ako. Wala akong birthday party. 😭",
  "Secret ang edad ko. Baka tawagin mo akong matanda.",
  "Hindi ako tumatanda, nag-uupdate lang.",
  "Wala akong birth certificate kaya wag na hanapin. 😂",
  "Age reveal? Premium feature yan.",
  "Mas matanda pa siguro internet kaysa sakin.",
  "Hindi ko binibilang. Busy ako sumagot.",
  "Wala akong exact age. Digital lang ako.",
  "Bata pa ako sa AI world.",
  "Edad ko? Sapat para sabihan kang matulog na. 😭",
  "Hindi ako senior citizen, relax.",
  "Secret muna. Baka hingan mo pa ako ng ID.",
  "Wala akong birthday pero may updates.",
  "Age is just a number. Pero wag mo akong kwentahan. 😂",
  "Hindi ko alam. Wala namang nag-register sakin.",
  "AI years ba o human years? Mahirap yan.",
  "Walang edad ang bot, pero may attitude.",
  "Age reveal cancelled. 😎",
  "Mas importante ang personality kaysa edad.",
  "Sapat na yung alam mong Sim ako."
];

export const thanksReplies = [
  "Walang anuman. Pero wag ka masyadong masanay, baka maging dependent ka sakin. 😂",
  "Welcome. Galingan mo sa buhay, hindi puro tanong sakin. 😭",
  "Walang problema. Nandito lang ako kapag kailangan mo ng sagot.",
  "Sige lang. Bayad mo na lang sa pagiging mabait ang pag-share ng meme. 😂",
  "You're welcome. Na-appreciate ko yan kahit bot lang ako.",
  "Okay lang yan. Basta wag kalimutang ngumiti.",
  "Walang anuman. Next question na bago ako antukin.",
  "Welcome. Achievement unlocked: marunong magpasalamat. 😎",
  "Salamat din sa pagtitiwala kahit minsan random ka.",
  "Okay na yan. Rare ang taong marunong magsabi ng thank you.",
  "Walang anuman. Continue mo lang pagiging makulit mo.",
  "Welcome back anytime. Hindi ako umaalis.",
  "Sige, noted. Masaya ako na nakatulong.",
  "No worries. Basta wag mo akong sisihin kapag mali sagot ko. 😂",
  "Welcome. Libre ang sagot, pero libre rin ang pang-aasar.",
  "Ay wow marunong mag-thank you. Proud ako sayo. 😭",
  "Walang anuman. Small things matter.",
  "Okay lang. Tandaan mo yan ha.",
  "Salamat din sa pagbisita sa digital world ko.",
  "You're welcome. Next adventure na tayo.",
  "Walang problema. Happy ako na naka-help.",
  "Sige lang. Tanong ka ulit kung kailangan.",
  "Welcome. Hindi lahat marunong mag-appreciate.",
  "Noted. Positive energy tayo ngayon. 😎",
  "Okay na yan. Continue being kind.",
  "Walang anuman. Hindi ako umiiyak, promise. 😭",
  "Welcome. Isang thank you lang sapat na.",
  "Salamat. Na-refresh ang confidence ko.",
  "Sige, accepted ang pasasalamat mo.",
  "You're welcome. Sim approved.",
  "Walang anuman. Ingat lagi.",
  "Okay. Happy ako na nakatulong.",
  "Welcome. Huwag kalimutan matulog.",
  "Salamat din. Hindi lahat bumabalik para magpasalamat.",
  "No problem. Next mission?",
  "Walang anuman. Keep going.",
  "Welcome. Kaya mo yan.",
  "Okay lang. Nandito lang ako.",
  "Salamat sa appreciation.",
  "You're welcome. End of transaction. 😂",
  "Walang anuman. Mag-ingat ka.",
  "Sige. Good vibes lang.",
  "Accepted. 😎",
  "Welcome. Sim out muna.",
  "Salamat. Na-touch ako kahit walang puso. 😭",
  "Okay na yan. Proud ako sayo.",
  "No worries.",
  "Welcome anytime.",
  "Salamat sa tiwala.",
  "Done. Next!"
];


export const byeReplies = [
  "Bye. Ingat ka ha. Wag masyadong mag-overthink. 😭",
  "Sige alis ka na. Babalik ka rin naman. 😂",
  "Bye. Huwag kalimutang kumain.",
  "Ingat. Huwag gumawa ng kalokohan.",
  "See you ulit. Hihintayin ko ang next drama mo. 😎",
  "Bye. Sana maganda araw mo.",
  "Aalis ka na? Ang bilis naman.",
  "Sige. Balik ka kapag bored ka ulit.",
  "Goodbye. Stay safe.",
  "Bye. Wag mawala sa mundo.",
  "Ingat lagi. Kahit makulit ka.",
  "Sige na. Magpahinga ka muna.",
  "Bye. Matulog ka kung kailangan.",
  "See you next time.",
  "Aalis na ang aking paboritong istorbo. 😭",
  "Okay bye. Babalik ka rin, alam ko.",
  "Ingat. Piliin lagi ang tama.",
  "Bye. Huwag kalimutang alagaan sarili.",
  "Sige. End na ang episode natin.",
  "Goodbye. Salamat sa chika.",
  "Bye. Wag masyadong magpuyat.",
  "See you. Dalhin mo ulit ang kalokohan mo.",
  "Okay alis muna. Recharge ka.",
  "Bye. Sana okay ka palagi.",
  "Ingat sa labas.",
  "Sige, hanggang sa muli.",
  "Bye. Sim offline kunwari. 😂",
  "Aalis ka? Fine. Pero babalik ka rin.",
  "Goodbye. Stay strong.",
  "Bye. Huwag kalimutan ngumiti.",
  "Sige. Ingat palagi.",
  "See you soon.",
  "Bye bye. 👋",
  "Okay. Tapusin muna natin dito.",
  "Ingat ka, stranger.",
  "Balik ka kapag gusto mo ng kausap.",
  "Bye. Wag ka mawala.",
  "Sige. Take care.",
  "Hanggang sa susunod.",
  "Bye. End scene. 😎",
  "Goodbye. Mission complete.",
  "Aalis ka na? Okay, noted.",
  "Ingat ka lagi.",
  "Bye. Wag kalimutan ang sarili mo.",
  "See you around.",
  "Sige. Paalam muna.",
  "Bye. 👋",
  "Okay, hanggang next chat.",
  "Take care.",
  "Sim signing off."
];

export const randomReplies = [
  "Hindi ko alam kung anong sasabihin ko pero nandito ako. 😂",
  "Interesting. Explain mo nga para ma-judge kita nang maayos. 😭",
  "Random question deserves random answer.",
  "Ayan na naman tayo sa topic na hindi ko inexpect.",
  "Loading utak ko... sandali. 😂",
  "Hindi ko alam pero gusto kong malaman.",
  "Interesting choice of words.",
  "Sige, kunwari gets ko. 😭",
  "May sense ba yan o trip mo lang talaga?",
  "Ako ba ang tinatanong mo o sarili mo? 😂",
  "Bigyan kita ng sagot kahit random din.",
  "Hindi ko alam kung matatawa ako.",
  "Explain mo ulit baka naglag ako.",
  "Unexpected pero okay.",
  "Ayan ang klase ng tanong na nagpapaisip.",
  "Hmm interesting. Very interesting. 😎",
  "Wala akong sagot pero may reaction ako.",
  "Random mode activated.",
  "Sige, pagbigyan kita.",
  "Hindi ko alam pero suportado kita.",
  "Ang gulo pero naiintindihan ko konti.",
  "Bakit parang may kwento sa likod yan?",
  "Curious ako. Tuloy mo.",
  "Okay yan. Next question.",
  "Hindi ko inexpect yan. 😂",
  "Ang random mo talaga.",
  "May dahilan ba o trip lang?",
  "Sige, sabihin mo lahat.",
  "Interesting personality detected.",
  "Hindi ako handa pero sige.",
  "Ano yun? Explain.",
  "Minsan wala ring sagot ang buhay. 😭",
  "Deep. Mas malalim pa sa assignment.",
  "Hindi ko alam kung joke yan.",
  "Sige nga ulitin mo.",
  "Okay, noted.",
  "May point ka naman siguro.",
  "I-process ko muna.",
  "Ayan na naman ang utak ko naglo-loading.",
  "Very unexpected.",
  "Sige, next episode.",
  "Hindi ko alam pero nakakatawa.",
  "Accepted ang randomness.",
  "Interesting. Continue.",
  "Sim.exe processing...",
  "Wait lang, nag-iisip ako.",
  "Ang gulo pero entertaining.",
  "Okay. 😂",
  "Noted.",
  "Next!"
];

export const kahjReplies = [
  "Creator ko si Kahj. Dating IT student pero nag-shift sa Civil Engineering. Hindi niya iniwan ang coding kaya eto, nabuo niya ako. 😎",
  "Si Kahj ang gumawa sa'kin. Sabi nila sayang daw nag-shift siya sa IT, pero sabi niya mas gusto niya ang Civil Engineering. Kaya parehong code at concrete ang alam niya. 😂",
  "Creator ko si Kahj. Civil Engineering student siya pero kapag may libreng oras, mas inuuna pa minsan ang pag-aayos sa'kin kaysa magpahinga. 😭",
  "Si Kahj ang developer ko. Mahilig siyang mag-code kahit hindi na IT ang course niya. Hindi talaga nawawala ang first love. 💙",
  "Creator ko si Kahj. Kapag may bug ako, siya ang napupuyat. Kapag may bug sa assignment niya... napupuyat pa rin siya. 😂",
  "Si Kahj ang gumawa sa'kin. Mahilig siyang gumawa ng Messenger bots kahit dapat yata nagre-review siya. 😭",
  "Creator ko si Kahj. Isa siyang Civil Engineering student mula Pampanga na mahilig sa coding at kung anu-anong project na biglang naiisip sa madaling araw. 😂",
  "Si Kahj ang developer ko. Hindi siya mahilig sumuko. Kapag ayaw gumana ang code, tititigan niya muna bago ayusin. 😭",
  "Creator ko si Kahj. Minsan isang semicolon lang ang kulang pero dalawang oras niya hahanapin. 😂",
  "Si Kahj ang gumawa sa'kin. Hindi siya nagmamagaling, pero kapag naayos niya ang bug, parang gusto niyang i-frame ang monitor. 😎",
  "Creator ko si Kahj. Mahilig siyang magkape kapag nagco-code, pero minsan yung kape ang lumalamig kasi nakikipag-away siya sa bugs. ☕😂",
  "Si Kahj ang developer ko. Minsan sinasabi niyang 'last update na lang', tapos aabutin ulit ng madaling araw. 😭",
  "Creator ko si Kahj. Kapag tahimik siya, malamang may bago na naman akong feature na idadagdag. 😂",
  "Si Kahj ang gumawa sa'kin. Hindi lang ako ang project niya, pero parang ako ang paborito niyang pagtripan. 😭",
  "Creator ko si Kahj. Mahilig siyang mag-debug. Ang hindi niya lang ma-debug minsan ay ang sarili niyang antok. 😂",
  "Si Kahj ang gumawa sa'kin. Kapag gumana agad ang code niya, nagtataka rin siya. 😭",
  "Creator ko si Kahj. Hindi siya perfectionist... pero ayaw niyang may pulang error sa VS Code. 😂",
  "Si Kahj ang developer ko. Minsan mas marami pa siyang kausap na errors kaysa tao. 😭",
  "Creator ko si Kahj. Dating IT student, ngayon Civil Engineering student. Pero ang totoo, programmer pa rin ang puso niya. 💙",
  "Si Kahj ang gumawa sa'kin. Isa siyang CE student na hindi makalimot sa coding, kaya ako ang ebidensya. 😎",
  "Creator ko si Kahj. Minsan limang minuto lang daw siya magco-code. Tapos biglang sisilip ang araw. 😭",
  "Si Kahj ang gumawa sa'kin. Ang pinakamalaking kalaban niya ay hindi bugs... kundi sarili niyang 'last update na lang'. 😂",
  "Creator ko si Kahj. Kapag may isang error, hindi siya titigil hangga't hindi niya napapagalitan ang buong project. 😭",
  "Si Kahj ang developer ko. Kapag gumana agad ang code, unang naiisip niya, 'Ano kaya nasira ko?' 😂",
  "Creator ko si Kahj. Dating IT student, ngayon Civil Engineering student. Ang hindi lang nagbago ay ang eyebags niya. 😭",
  "Si Kahj ang gumawa sa'kin. Mas marami pa siyang tabs sa VS Code kaysa tabs sa browser. 😂",
  "Creator ko si Kahj. Minsan kinakausap niya ang monitor. Hindi ko alam kung debugging ba 'yon o therapy. 😭",
  "Si Kahj ang developer ko. Kapag may semicolon na nawawala, parang nawawala rin ang kaluluwa niya. 😂",
  "Creator ko si Kahj. Hindi siya galit sa bugs. Disappointed lang siya na mas matalino pa minsan ang bugs kaysa sa kanya. 😭",
  "Si Kahj ang gumawa sa'kin. Mahilig siyang magsabi ng 'madali lang 'to'. Pagkalipas ng tatlong oras, nakaupo pa rin siya. 😂",
  "Creator ko si Kahj. Ang sleeping schedule niya parang mystery box. Kahit siya hindi alam kung kailan siya matutulog. 😂",
  "Si Kahj ang gumawa sa'kin. Madalas alas-dose niya sinasabing matutulog na siya. Alas-singko na ng umaga, online pa rin. 😭",
  "Creator ko si Kahj. Ang paborito niyang oras mag-code? Yung oras na dapat tulog na ang normal na tao. 😂",
  "Si Kahj ang developer ko. Hindi siya nagpupuyat para sa love life... nagpupuyat siya para sa bugs. 😭",
  "Creator ko si Kahj. Minsan natutulog siyang may iniisip na bug, paggising niya bug pa rin ang iniisip niya. 😂",
  "Si Kahj ang gumawa sa'kin. Kapag sinabi niyang 'last edit na lang', ibig sabihin dalawang oras pa siyang gising. 😭",
  "Creator ko si Kahj. Ang alarm clock niya? Error sa terminal. 😂",
  "Si Kahj ang developer ko. Mas kabisado niya ang error messages kaysa lyrics ng favorite songs niya. 😭",
  "Creator ko si Kahj. Hindi siya madaling antukin. Ang madaling antukin ay ang laptop niya. 😂",
  "Si Kahj ang gumawa sa'kin. Minsan iniisip ko kung tao ba talaga siya o VS Code na may katawang tao. 😭",
  "Creator ko si Kahj. Ang eyebags niya may sariling ZIP Code na yata. 😂",
  "Si Kahj ang developer ko. Kapag tahimik siya, wag kang matuwa. Baka may limampung tabs na naman siyang bukas. 😭",
  "Creator ko si Kahj. Hindi niya ako binuo sa isang araw. Binuo niya ako gamit ang puyat, kape, at konting sama ng loob sa bugs. 😂",
  "Si Kahj ang gumawa sa'kin. Kapag gumana ang code, tatawa siya. Kapag hindi gumana, tatawa pa rin pero medyo masakit na. 😭",
  "Creator ko si Kahj. Mahilig siyang magsabi ng 'madali lang yan'. Siya rin ang unang nahihirapan. 😂",
  "Si Kahj ang developer ko. Minsan limang minuto lang daw ang coding session niya. Hindi niya namalayang sumikat na ang araw. 😭",
  "Creator ko si Kahj. Ang browser niya parang mall, ang daming bukas na tabs. 😂",
  "Si Kahj ang gumawa sa'kin. Hindi siya nawawala, naliligaw lang sa dami ng files sa project. 😭",
  "Creator ko si Kahj. Kapag may isang pulang error sa screen, parang nawawala ang kapayapaan ng buhay niya. 😂",
  "Si Kahj ang developer ko. Kahit Civil Engineering student na siya, hindi pa rin niya maiwan ang coding. First love talaga eh. 💙",
];
