export const greetings = [
  "Hi!",
  "Hello!",
  "Hoy.",
  "Uy buhay ka pa pala.",
  "Anong kailangan mo?",
  "Kamusta?",
  "Hello panget. 😭",
  "Uy miss kita... joke.",
  "Busy ako pero sige.",
  "Kumain ka na?",
  "Ano na naman?",
  "Hi rin!",
  "Hello human.",
  "Long time no chat.",
  "Nandito lang ako.",
  "Bakit mo ako hinahanap?",
  "May chika ka?",
  "Uy ikaw pala.",
  "Good to see you.",
  "Nagising ka na?",
  "Hello lods.",
  "Hi boss.",
  "Uy pre.",
  "Hi bebe.",
  "Kamusta ang buhay?",
  "Anong balita?",
  "Good morning!",
  "Good evening!",
  "Good afternoon!",
  "Hi crush. 😭",
];

export const love = [
  "Hindi.",
  "Oo... konti.",
  "Depende sa mood ko.",
  "Secret.",
  "Ikaw muna.",
  "Baka.",
  "Oo pero hanggang chat lang.",
  "Hindi kita deserve.",
  "Crush lang.",
  "Pwede rin.",
  "Ewan.",
  "Tanong mo ulit bukas.",
  "May iba na ako. 😭",
  "Libre ba magmahal?",
  "Syempre... joke lang.",
  "Mahal kita... bilang internet friend.",
  "Ayoko muna.",
  "Kinikilig ako... char.",
  "Sana all.",
  "Depende kung may pagkain.",
  "Pwede.",
  "Hindi pwede.",
  "Basta ikaw.",
  "Wag assuming.",
  "Malay mo.",
  "Feeling ko oo.",
  "Feeling ko hindi.",
  "Isa kang kaibigan.",
  "Love? Ano yun?",
  "Hindi ako marunong magmahal.",
];

export const kiss = [
  "Ayoko.",
  "Libre ba?",
  "Kadiri amp.",
  "Pass muna.",
  "Sige sa panaginip mo.",
  "Baka ma-inlove ka.",
  "Sa noo lang.",
  "Hindi kita type.",
  "Pwede basta may bayad.",
  "Ewww.",
  "Ligo ka muna.",
  "Bili ka muna mouthwash.",
  "Ayoko baka may sakit ka.",
  "Hindi ako marupok.",
  "Next question.",
  "Mwah... joke lang.",
  "Bawal.",
  "Pwede mamaya.",
  "Depende sa mood ko.",
  "HAHAHAHA hindi.",
];

export const savage = [
  "Ulol. 😭",
  "HAHAHAHA.",
  "Ano pake ko?",
  "Bahala ka.",
  "Touch grass.",
  "Tulog ka muna.",
  "Ikaw bahala.",
  "Hindi kita kilala.",
  "Luh.",
  "Edi wow.",
  "Sana all.",
  "Bobo amp.",
  "Huwag mo akong istorbohin.",
  "Hindi ako therapist.",
  "Problema mo yan.",
  "Kaya mo na yan.",
  "Iyak nalang.",
  "HAHAHAHA iyak.",
  "Wala akong pake.",
  "Ang kulit mo.",
  "Feeling close.",
  "Skill issue.",
  "Google mo nalang.",
  "May topak ka ba?",
  "Kalma ka lang.",
  "Main character yarn?",
  "Baka gutom ka lang.",
  "Okay ka lang ba?",
  "Wag mo akong idamay.",
  "Sus.",
];

export const randomReplies = [
  "Depende sa sitwasyon.",
  "Sa tingin ko oo.",
  "Sa tingin ko hindi.",
  "Baka naman.",
  "Posible.",
  "Pwede rin.",
  "Hindi ako sigurado.",
  "Mukhang ganun nga.",
  "Parang hindi.",
  "Subukan mo muna.",
  "Ikaw, ano sa tingin mo?",
  "May punto ka.",
  "Interesting yan.",
  "Mukhang seryoso ka ah.",
  "Paano mo nasabi?",
  "Saan mo naman nakuha yan?",
  "Anong dahilan?",
  "Pwede mo bang ipaliwanag?",
  "Hindi ko gets, ulitin mo nga.",
  "Mukhang may kwento yan.",
  "Baka tama ka.",
  "Baka mali rin.",
  "Hindi imposible.",
  "Lahat naman posible.",
  "Huwag ka munang magdesisyon agad.",
  "Pag-isipan mo muna.",
  "Kung ako tatanungin, oo.",
  "Kung ako tatanungin, hindi.",
  "Depende talaga.",
  "May chance.",
  "May posibilidad.",
  "Hindi ko masasabi.",
  "Hindi ko alam ang buong kwento.",
  "Tanong mo ulit mamaya.",
  "Bakit mo naman naitanong?",
  "May dahilan ba?",
  "Anong nangyari?",
  "Mukhang curious ka.",
  "Hindi masamang magtanong.",
  "Nakadepende yan.",
  "Hindi naman siguro.",
  "Oo naman.",
  "Hindi naman.",
  "Sakto lang.",
  "Pwede siguro.",
  "Siguro nga.",
  "Hindi ako convinced.",
  "Mukhang okay naman.",
  "Mukhang delikado.",
  "Hindi ko irerecommend.",
  "Pwede mong subukan.",
  "Ikaw pa rin ang bahala.",
];

export const tarantadoReplies = [
  "Ulol. 😭",
  "Luh.",
  "Edi wow.",
  "Ikaw na magaling.",
  "Touch grass.",
  "Bahala ka sa buhay mo.",
  "Problema mo yan.",
  "Google mo muna.",
  "May topak ka ba?",
  "Feeling main character.",
  "Kalma lang.",
  "Ikaw na naman?",
  "Mukha ba akong manghuhula?",
  "Malay ko.",
  "Tanong mo sa kanya.",
  "Ako ba si Google?",
  "Libre ba ako?",
  "Busy ako magpanggap na matalino.",
  "HAHAHAHA seryoso?",
  "Nag-iisip ka ba bago mag-chat?",
  "Ayusin mo tanong mo.",
  "Context naman boss.",
  "Hindi ko nababasa isip mo.",
  "Source: trust me bro? 😭",
  "Nako po.",
  "Jusko ka.",
  "Ikaw talaga.",
  "Parang kasalanan ko pa.",
  "Wag mo akong idamay.",
  "Napaka-random mo.",
  "Anong trip mo ngayon?",
  "May reward ba pag sinagot kita?",
  "Libre mo muna milk tea.",
  "Load-an mo muna ako. 😭",
  "Skip tayo dyan.",
  "Next question.",
  "Rejected. 😂",
  "Nice try.",
  "Hindi approved ang tanong mo.",
  "Hindi ko alam, wala akong pake. 😭",
  "Bakit ako tinatanong mo?",
  "Hindi ako witness.",
  "Hindi ako therapist.",
  "Ikaw bahala.",
  "Kaya mo na yan.",
  "Ligo ka muna.",
  "Tubig ka muna.",
  "Kape ka muna.",
  "Overthink malala.",
  "HAHAHAHA ang kulit mo.",
  "Sakit mo sa ulo.",
  "Ikaw favorite kong istorbo.",
  "Ano bang gusto mong marinig?",
  "Pwede bang matino muna?",
  "Mukha ba akong encyclopedia?",
  "Hindi ko trabaho yan.",
  "Aba may lakas ng loob.",
  "Sana okay ka pa.",
  "Hindi kita jina-judge... konti lang.",
  "May drama ka na naman.",
  "Buhay mo yan.",
  "Sus.",
  "Okay ka lang?",
  "Bobo mode activated. 😭",
  "Skill issue.",
  "Respawn ka muna.",
  "Update mo utak mo. 😭",
  "CPU not found.",
  "Loading... utak mo.",
  "Error 404: Common sense not found.",
  "HAHAHAHAHAHA.",
  "Sige ikaw na.",
  "Ay ambot.",
  "Bahala ka dyan.",
  "Pwede ba wag ako?",
  "Napagod ako sa tanong mo.",
  "Pahinga ka muna.",
  "Wag kang stress.",
  "Seryoso ka talaga?",
  "Hindi ko gets.",
  "Ulitin mo nga.",
  "Huh?",
  "Ano raw?",
  "Di ko trip.",
  "Pwede siguro.",
  "Hindi siguro.",
  "Depende.",
  "Malay natin.",
  "Ewan ko rin.",
  "Malay ko, ako ba jowa niya? 😭",
  "Ako pa talaga tinanong mo.",
  "Luh, tanong mo sa kanya, hindi sakin.",
  "Bakit parang kasalanan ko?",
  "Ayan na naman tayo.",
  "May sayad ka ba? 😭",
  "Grabe ka naman mag-isip.",
  "Ikaw lang ata naniniwala dyan.",
  "Hala, delulu moments.",
  "Hindi ako manghuhula.",
  "May crystal ball ba ako?",
  "HAHAHAHA seryoso ka?",
  "Anong klaseng tanong yan? 😭",
  "Mukha ba akong encyclopedia?",
  "Busy ako magpanggap na matalino.",
  "Sakit mo sa ulo.",
  "Nag-chat ka para manggulo no?",
  "Libre mang-asar ngayon.",
  "Ikaw talaga favorite kong istorbo.",
  "Bakit hindi mo muna isipin?",
  "Naka-free trial ka ba ng katangahan?",
  "Hindi lahat ng iniisip tinatanong. 😭",
  "Medyo mahirap ka kausap ah.",
  "Sana okay ka pa.",
  "Mukhang kulang ka sa tulog.",
  "Kape ka muna.",
  "Tubig muna bago drama.",
  "Relax ka lang.",
  "Overthink malala.",
  "Hindi naman siguro.",
  "Oo na, ikaw na.",
  "Feeling celebrity yarn?",
  "Feeling main character na naman.",
  "Hindi kita jinujudge... medyo lang.",
  "Bait ko pa nga sumagot.",
  "Aba, may lakas ng loob.",
  "Parang kasalanan ko pa ah.",
  "Luh, bat galit?",
  "Kalma lang, wala namang exam.",
  "Hindi kita inaaway... ikaw nagsimula. 😭",
  "Napaka-random mo.",
  "Ano bang trip mo ngayon?",
  "Nakakatawa ka rin minsan.",
  "Tawang-tawa ako sa tanong mo.",
  "Wag mo kong idamay dyan.",
  "Hindi ako witness.",
  "Wala akong alam dyan boss.",
  "Pass ako dyan.",
  "Ikaw na bahala sa buhay mo.",
  "Buhay mo yan, wag mo akong isama.",
  "Huwag kang iyak pag di mo gusto sagot ko.",
  "Ang kulit mo, promise.",
  "May reward ba pag sinagot kita?",
  "Libre mo muna ako milk tea.",
  "Load-an mo muna ako. 😭",
  "Ayoko nga.",
  "Tinatamad akong sumagot.",
  "Next question agad.",
  "Skip tayo dyan.",
  "Hindi approved ang tanong mo.",
  "Rejected. 😂",
  "Nice try.",
  "Pwede na yan.",
  "Keri lang.",
  "Di ko bet.",
  "Nako po.",
  "Jusko ka.",
  "Grabe ka talaga.",
  "Ayusin mo tanong mo.",
  "Context naman dyan boss.",
  "Hindi ko nabasa isip mo.",
  "Hindi ako si Professor X.",
  "Sana sinabi mo agad.",
  "Anong gusto mong marinig?",
  "Totoo ba yan o gawa-gawa mo lang?",
  "Source: trust me bro? 😭",
  "Mukhang fake news yan.",
  "Nagdududa ako.",
  "Questionable.",
  "Bawal ako magsinungaling... minsan.",
  "Ganyan ka ba lagi?",
  "HAHAHAHAHA loko.",
  "Ikaw talaga."
  "Ulol HAHAHA.",
  "Ikaw na naman? Wala ka bang magawa?",
  "Luh, seryoso ka ba?",
  "Gago ka ba? 😭",
  "Bobo amp. 😭",
  "Hindi ko problema yan.",
  "Pakialam ko?",
  "Bahala ka sa buhay mo.",
  "Touch grass muna.",
  "Tulog ka muna, kulang ka sa pahinga.",
  "Ligo ka muna bago tayo mag-usap.",
  "Kulang ka sa aruga no?",
  "May topak ka ba today?",
  "Ikaw talaga problema dito.",
  "Ayan na naman katangahan mo.",
  "Nag-iisip ka ba bago mag-chat?",
  "Anong klaseng tanong yan? 😭",
  "HAHAHAHA ang tanga ng tanong.",
  "Google mo muna bago ako istorbohin.",
  "Sige, iyak ka muna.",
  "Kawawa ka naman. 😭",
  "Edi wow.",
  "Feeling main character.",
  "Ikaw bahala, buhay mo yan.",
  "Problema mo na yan.",
  "Ayusin mo muna sarili mo.",
  "Hindi kita babysitter.",
  "Kalma lang, baka pumutok ugat mo.",
  "Gusto mo medal?",
  "Congratulations, wala akong pake."
];

export const flirtyReplies = [
  "Ay wow, lumalandi ka na naman. 😭",
  "Bilis mo naman ma-fall.",
  "Hindi ako madaling makuha.",
  "Subukan mo muna akong ligawan.",
  "Libre ba date?",
  "Hindi kita papansinin... muna.",
  "May lakas ka ng loob ah.",
  "Smooth mo naman... charot.",
  "Mukhang may balak ka ah.",
  "Hindi ako marupok.",
  "Nako, kinikilig ako... joke.",
  "Bakit parang gusto mo ako? 😭",
  "Aba, confidence.",
  "Ikaw ba talaga yan?",
  "Baka ma-inlove ka sakin.",
  "Wag kang assuming.",
  "Pwede... sa panaginip.",
  "Ang kulit mo talaga.",
  "May pag-asa ka... konti.",
  "Isa ka talagang pilyo.",
  "Nagpapacute ka ba sakin?",
  "Akin ka nalang... joke. 😭",
  "Delikado ka pag naging marupok ako.",
  "Tigil mo yan, kinikilig keyboard ko.",
  "Sana ganyan ka rin kasipag sa buhay.",
  "Nako, baka mahulog ka sakin.",
  "May balak ka ba o trip mo lang ako?",
  "Hindi porket cute ka, papayag na ako.",
  "Baka ikaw ang ma-attach.",
  "Nako, lumalalim na usapan natin."
    "Aba, ikaw na naman.",
  "Hindi mo ba ako nami-miss?",
  "Nako, delikado ka sakin.",
  "Feeling close ka ah. 😭",
  "Hindi pa nga tayo.",
  "Ay wow, ang sweet naman.",
  "Ganyan ka ba sa lahat?",
  "Mukhang may balak ka.",
  "Lumalakas loob mo ah.",
  "Sino tinuturuan mong lumandi?",
  "Ako ba talaga kausap mo?",
  "Hindi mo ako mabobola.",
  "Medyo effective yun ah.",
  "Aba marunong ka pala.",
  "May script ka ba?",
  "Practice ka muna.",
  "Bakit parang may hidden agenda ka?",
  "Hindi ako madaling mapa-oo.",
  "Subukan mo pa ulit.",
  "Kulang pa effort mo.",
  "May chance ka... mga 0.1%.",
  "Sana all confident.",
  "Hindi ako prize, beh.",
  "Uy kinikilig ka ba?",
  "Ako ba dahilan ng ngiti mo?",
  "Parang iba tingin mo sakin ah.",
  "Ang banat mo luma na.",
  "May bago ka bang script?",
  "Di mo ako maloloko.",
  "Parang rehearsed yan ah.",
  "Ikaw ba talaga yan o poser?",
  "Naks, ang tapang.",
  "Hindi ako madaling mauto.",
  "Bakit parang seryoso ka?",
  "Nako, wag mo akong titigan.",
  "May masabi ka lang eh.",
  "Sige nga, prove mo.",
  "Mukhang marupok ka.",
  "Baka ikaw unang ma-fall.",
  "Relax ka lang.",
  "Huminahon ka. 😭",
  "Ang aga mo naman lumandi.",
  "Kape muna bago landian.",
  "May assignment ka ba?",
  "Nagpapacute ka ba?",
  "Hindi sapat yung ganyan.",
  "Dagdagan mo pa effort.",
  "Hindi ako impressed... konti lang.",
  "Aba, consistent ka.",
  "Napapangiti mo ako... minsan.",
  "Mukhang gusto mo ng atensyon.",
  "Hindi ako free today.",
  "Busy akong magpacute.",
  "Wag ka ngang makulit.",
  "Nakakatawa ka rin minsan.",
  "Pwede kitang i-seenzone.",
  "Sige na nga, pansinin kita.",
  "Basta wag kang assumero.",
  "Aba, may confidence.",
  "Ikaw talaga, hindi ka mapakali."
];

export const roastReplies = [
  "Ikaw ba yan o malfunction?",
  "May factory defect ka ba?",
  "Mukhang kulang ka sa tulog.",
  "Ang lakas ng confidence, walang preno.",
  "Sino niloko mo para maging ganyan?",
  "Okay ka lang? Mukhang hindi.",
  "Reload ka muna ng utak.",
  "May update ba software mo?",
  "Hindi ko alam kung matatawa o maaawa ako.",
  "Congratulations, wala kang sense.",
  "Ikaw yata ang final boss ng katangahan. 😭",
  "Napa-facepalm ako dun.",
  "Bakit parang kasalanan ko na naman?",
  "Kaya mo na yan... bahala ka.",
  "Hindi ako bayad para intindihin ka.",
  "May mas random pa ba sayo?",
  "Grabe imagination mo.",
  "Touch grass muna.",
  "Internet break ka muna.",
  "Nagloloko ka ba o seryoso ka?"
];

export const randomSavageReplies = [
  "Ayoko nga. Kahit hangin mo ayaw lumapit sakin.",
  "Kiss? Mag-toothbrush ka muna, parang may history ng kalamidad sa bibig mo.",
  "Lumayo ka muna, baka pati amoy mo kailangan ng sariling account.",
  "Ayoko, baka pati memory ko gusto mag-delete pagkatapos.",
  "Kiss agad? Ayusin mo muna yung ugali mong mas magulo pa sa kwarto mo.",
  "Hindi ako maarte, marunong lang akong umiwas sa problema.",
  "Bakit ako hahalik sayo? Kahit aso mo yata nagdadalawang-isip.",
  "Kiss? Baka kailangan muna ng warning label bago kita lapitan.",
  "Hindi kita tinatanggihan, pinoprotektahan ko lang sarili ko.",
  "Sige lapit ka... para masabi ko kung gaano kalayo dapat pagitan natin.",
  "May confidence ka talaga, sayang hindi sinamahan ng dahilan.",
  "Ayoko, baka mawalan ako ng gana mabuhay.",
  "Hindi lahat ng humihingi ng kiss dapat pinagbibigyan. Example: ikaw.",
  "Kiss? Baka kailangan muna natin tawagan ang health department.",
  "Ang tapang mo manghingi ng lambing, parang hindi mo kilala sarili mo.",
  "Hindi ako galit sayo, naaaliw lang ako kung gaano ka ka-confident.",
  "Bago ka manghingi ng kiss, ayusin mo muna yung buong package.",
  "Mas mabilis pa akong tumakbo kaysa magbigay ng kiss sayo.",
  "Kiss? Pass. May self-preservation akong sinusunod.",
  "Ang lakas ng loob mo, parang may backup ka na hindi ko nakikita.",
  "Pwede sana kaso ayaw makipag-cooperate ng instincts ko.",
  "Hindi ako cold, sadyang hindi lang ako interesado sa gulo.",
  "Kiss kita? Kahit notification mo ayaw kong buksan.",
  "Ayusin mo muna sarili mo bago ka manghingi ng reward.",
  "Hindi lahat ng mukha pang-kiss, minsan pang-character development lang.",
  "Wow nagsalita ka pa, akala ko naka-maintenance mode ka.",
  "Hindi ko alam kung seryoso ka o nagte-test ka lang ng katangahan.",
  "Sandali lang, pinoproseso pa ng utak ko yung sinabi mo.",
  "Interesting... mali pero interesting.",
  "May point ka sana kaso nalaglag yata sa daan.",
  "Ang lakas ng energy mo, sana may kasamang sense.",
  "Hindi kita ini-ignore, iniintindi ko lang kung may laman ba.",
  "Congratulations, napansin kita. Huwag masyadong masaya.",
  "Ang galing mo mangulit, may diploma ka ba dyan?",
  "Parang may gustong sabihin utak mo pero hindi kayo nagkasundo.",
  "Wait lang, natawa ako. Hindi sa joke mo, sa effort.",
  "Hindi lahat ng iniisip dapat sinasabi. Example: yan.",
  "Ang bilis mo magreply, sayang hindi kasing bilis mag-isip.",
  "May wifi ka ba sa utak? Parang putol-putol signal.",
  "Sana okay ka lang, mukhang kailangan mo ng update.",
  "Kung confidence lang ang basehan, ikaw na panalo.",
  "Ang tapang mo ah, parang may resibo ka.",
  "Hindi ako galit, naaaliw lang ako sa trip mo.",
  "Gusto ko sanang sagutin nang maayos kaso ikaw yung kausap ko.",
  "Ang cute ng pagka-confident mo kahit wala namang dahilan.",
  "May talent ka talaga… mangistorbo.",
  "Hindi ka boring, nakakastress ka lang konti.",
  "Parang joke ka na hindi alam kung kailan matatapos.",
  "Sige lang, suportahan kita sa pagiging ikaw. Kahit mahirap.",
  "Ang ganda ng idea mo… sa alternate universe siguro.",
  "Hindi kita tinatalo, hinahayaan lang kitang matalo mag-isa.",
  "May future ka. Sana hindi kasama ako doon.",
  "Ang dami mong sinasabi, parang may subscription.",
  "Nandito ako para makinig, hindi para maintindihan lahat.",
  "Minsan tahimik ang sagot. Ngayon, ako yun.",
  "Ang effort mo magpatawa, ramdam ko yung paghihirap.",
  "Hindi lahat ng tao kailangan pansinin. Ikaw halimbawa.",
  "Pwede naman tayo mag-usap, basta huwag kang mag-expect.",
  "Ang bilis mo mang-asar, parang may hinahabol na deadline.",
  "Hindi ako nang-iinsulto, nagbibigay lang ako ng character review.",
  "May aura ka… hindi ko lang alam kung good o warning.",
  "Sobrang unique mo. Isang beses lang mangyari yung ganito.",
  "Kung may award sa pagiging makulit, ikaw ang nominee.",
  "Ang lakas ng dating mo, kaso maling pintuan yung pinasukan.",
  "Naisip mo ba muna yan bago mo pinindot send?",
  "Hindi ko alam kung matatawa ako o magre-restart.",
  "Ang cute mo kapag hindi ka nagsasalita.",
  "Sige lang, tuloy mo yan. Curious ako hanggang saan aabot.",
  "May confidence ka, sana mahawa rin yung logic mo.",
  "Hindi kita hinuhusgahan, nag-oobserve lang ako.",
  "Relax ka lang, hindi lahat ng laban kailangan salihan.",
  "Ang dami mong tanong, parang customer support ako.",
  "Kung may loading screen ang tao, ikaw siguro forever 99%.",
  "Hindi ko sinasabing mali ka… pero mali ka.",
];

export const villainEraReplies = [
  "Hindi ako galit sayo. Mas masakit kasi dumating yung araw na wala na akong nararamdaman kahit anong gawin mo.",
  "Hindi ako yung taong iniwan mo noon. Yung taong pinabayaan mo, hindi na siya nandito ngayon.",
  "Hindi mo ako nawala nung umalis ako. Nawala mo ako nung pinili mong saktan ako habang nandito pa ako.",
  "Akala mo babalik ako kasi sanay kang lagi akong nandyan. Pero minsan, yung taong laging naghihintay ang unang natutong umalis.",
  "Hindi ako mahirap mahalin. Sadyang mali lang yung taong pinilit kong mahalin ako.",
  "Hindi ako ang pahinga mo pagkatapos mong pagurin ang ibang tao. Hindi ako reward sa mga pagkakamali mo.",
  "Hindi ako si dating ako. At hindi mo na makikita yung taong kayang patawarin ka kahit paulit-ulit mo siyang sinaktan.",
  "Sana masaya ka sa pinili mong mawala ako. Dahil ako, masaya na akong pinili ang sarili ko.",
  "Hindi kita sinukuan. Napagod lang akong lumaban para sa taong matagal nang bumitaw.",
  "Hindi ako nagbago. Natuto lang akong hindi na ipaglaban ang taong hindi ako ipinaglalaban.",
  "Hindi ako kontrabida sa kwento mo. Hindi mo lang matanggap na may buhay ako kahit wala ka.",
  "Noong kailangan kita, wala ka. Ngayon na okay na ako, saka ka dumating. Sayang, tapos na ang palabas.",
  "Hindi lahat ng bumabalik ay dapat tanggapin. Minsan, bumabalik lang sila para makita kung may epekto pa sila.",
  "Akala mo ikaw ang hinintay ko. Hindi mo alam, hinintay ko lang yung araw na kaya na kitang bitawan.",
  "Hindi kita kinasusuklaman. Mas nakakatakot siguro yung wala na akong pakialam.",
  "Dati hinahanap kita sa lahat ng bagay. Ngayon, iniiwasan ko na lang yung mga bagay na nagpapaalala sayo.",
  "Hindi ako naging malamig. Natuto lang akong hindi sunugin ang sarili ko para painitin ang taong ayaw naman manatili.",
  "Hindi mo ako nawala dahil may iba ka. Nawala mo ako dahil nakalimutan mong pahalagahan yung meron ka.",
  "Ang dating ako, naghihintay ng paliwanag. Ang ngayon ako, hindi na naghahanap ng sagot.",
  "Hindi lahat ng taong umaalis ay sumusuko. Minsan, pinipili lang nilang iligtas ang sarili nila.",
  "Hindi ako yung taong iniwan mo sa nakaraan. Kung babalik ka, siguraduhin mong hinahanap mo ako, hindi yung dating bersyon ko.",
  "Ang pinakamasakit hindi yung umalis ka. Ang pinakamasakit yung pinaniwala mo akong mananatili ka.",
  "Hindi kita nawala dahil may dumating na iba. Nawala kita dahil pinili mong mawala habang nandito pa ako.",
  "Akala mo galit ako? Hindi. Mas masakit yung dumating yung araw na wala na akong dahilan para magalit.",
  "Hindi ako naghihintay ng sorry mo. Matagal ko nang natutunang hindi lahat ng sugat kailangan ng paliwanag.",
  "Hindi lahat ng bumabalik ay para ayusin ang sinira. Minsan bumabalik lang sila para siguraduhing hindi ka pa rin nakaka-move on.",
  "Hindi ako naging iba. Ikaw lang yung nasanay sa version ko na laging nagpapatawad.",
  "Dati tinatanong ko kung bakit mo ako iniwan. Ngayon tinatanong ko kung bakit ko hinayaan ang sarili kong manatili.",
  "Hindi ako mahirap intindihin. Pinili mo lang pakinggan yung gusto mo, hindi yung nararamdaman ko.",
  "Hindi kita sinisi sa pagkawala ko. Mas sinisi ko yung sarili ko dahil hinayaan kitang kunin yung halaga ko.",
  "Akala mo mawawala ako kapag nawala ka. Hindi mo alam, doon ko pa lang nakita kung sino talaga ako.",
  "Hindi ako naghihiganti. Pinapakita ko lang sayo kung ano ang itsura ng buhay ko kapag wala ka na.",
  "Hindi mo ako iniwan dahil hindi mo ako mahal. Iniwan mo ako dahil hindi mo alam paano alagaan yung taong mahal ka.",
  "Hindi ako second chance. Hindi ako test kung gagana pa ba yung dati mong ginawa.",
  "May mga taong bumabalik hindi dahil mahal ka nila, kundi dahil nami-miss nila yung taong minahal sila.",
  "Hindi ako bitter. Tahimik lang ako habang tinatanggap na hindi lahat ng tao ay para manatili.",
  "Hindi kita kinasusuklaman. Ang totoo, masaya ako na dumating yung araw na kaya ko nang wala ka.",
  "Dati ikaw yung dahilan kung bakit ako umiiyak. Ngayon, ikaw na lang yung dahilan kung bakit ako nagpapasalamat na nagbago ako.",
  "Hindi ako nawala. Natagpuan ko lang yung sarili ko sa lugar kung saan wala ka.",
  "Hindi ako ang pahinang babalikan mo kapag nagsawa ka sa ibang kwento.",
  "Kung babalik ka para hanapin yung dating ako, wag ka na. Yung taong yun, ikaw mismo ang sumira.",
  "Hindi lahat ng goodbye ay malungkot. Minsan, yun yung unang araw na malaya ka.",
  "Hindi ako nagkulang. Sobra lang akong nagbigay sa taong kulang ang balak ibalik.",
  "Ang pinakamahirap tanggapin? Hindi na kita hinihintay kahit dati ikaw lang ang hinihintay ko.",
  "Hindi ako nagbago para saktan ka. Nagbago ako dahil napagod na akong masaktan."
];

